### ISSUE TITLE
GoogleLogin cannot change button styling

### ISSUE THREAD

**Issue by ropholuo** [MomenSherif/react-oauth#102]
Hi, I am new to JS and I am not sure if something is off from my end, but I try to style the button with`<GoogleLogin
            onSuccess={(credentialResponse) => {
              responseGoogle(credentialResponse);
            }}
            onError={() => {
              console.log("Login Failed");
            }}
            text="Sign in with Google"
            theme="filled_black"
            logo_alignment="left"
          />`, and yet it still shows up as the default button with text as "sign in as ...". Is there anything else I need to do?

**Comment by MomenSherif** [comment]
text needs to be signin_with
You can check allowed values in the README

**Comment by ropholuo** [comment]
> text needs to be signin_with You can check allowed values in the README

Ty for the quick reply. I did check the docu but I thought it was entirely arbitrary.

**Comment by MomenSherif** [comment]
Unofrtunately specific values are allowed only

**Comment by ropholuo** [comment]
Is there a way I may change the theme from the one with user info to the one with plain text? I do get the plain text button with `useGoogleLogin` but I'd prefer `GoogleLogin`
![image](https://user-images.githubusercontent.com/78669543/193626975-27a69877-5d41-4506-8fa8-5044ca03dec0.png)

**Comment by MomenSherif** [comment]
Use medium size

**Comment by ropholuo** [comment]
> Use medium size

Really appreciate it!
