### ISSUE TITLE
"flow : auth-code" : : Getting Refresh Token on each authorization

### ISSUE THREAD

**Issue by asit-behera** [MomenSherif/react-oauth#103]
I used react-OAuth in react and I successfully get "code" but each time I get code, after generating tokens in the backend I get a refresh token. In Ideal conditions, we should get a Refresh token once, when we give consent for the first time. I am using [googleapis](https://www.npmjs.com/package/googleapis) in the nodejs app. And the same is also mentioned there.

Thank you.
Please mention if am missing out on something.

**Comment by MomenSherif** [comment]
It's handled by google, each login will have new code which exchanged for new tokens

https://developers.google.com/identity/protocols/oauth2/web-server#exchange-authorization-code

**Comment by ievgennaida** [comment]
@asit-behera 
Just out of the curiosity do you need access token from you backend to access any of the google services?
The same question for the frontend part, are you using access token on a frontend to request any of the APIs?

**Comment by asit-behera** [comment]
@ievgennaida 
I am storing the refresh token in my persistent storage.
and am fetching all data from from google in backend only.
My frontend is only responsible to send me the code after authrozation.
