### ISSUE TITLE
Is there a reason `credential` and `select_by` are optional in `CredentialResponse`?

### ISSUE THREAD

**Issue by hossameldeen** [MomenSherif/react-oauth#104]
`credential` and `select_by` are optional in `CredentialResponse`. Is there a particular reason for that?

https://github.com/MomenSherif/react-oauth/blob/aac1c931d13dc719afd99467ce8d97adba5477be/packages/%40react-oauth/google/src/types/index.ts#L55-L66

The [reference](https://developers.google.com/identity/gsi/web/reference/js-reference#CredentialResponse) has no mention of them being optional. Have you faced a case where they were?

Thanks!

**Comment by MomenSherif** [comment]
They will be optional if login failed, but you will not face this as it will fire onError & onSuccess for @react-oauth/google

**Comment by hossameldeen** [comment]
I see, thanks 👍
