### ISSUE TITLE
Get credentials with custom button

### ISSUE THREAD

**Issue by christophe13012** [MomenSherif/react-oauth#105]
Hello, thanks for this package.
Is it possible to get credientialResponse with custom buttons ? (and not tokenResponse)
thanks for your help

**Comment by tarunsoftprodigy** [comment]
Hey @christophe13012, did you figure it out?

**Comment by MomenSherif** [comment]
Hi!,
you can but with authorization code  flow, after exchanging the code with your backend you will get access, refresh, and id tokens

or if you are using it in implicit flow to get access token you can send request to google API to get user info

**Comment by raj2k00** [comment]
Hi @MomenSherif  Is there any direct way to get user credentials with custom button? Can you provide some examples for it?

**Comment by NisargIO** [comment]
Would love to see this

**Comment by theviralboy** [comment]
You can get the user's credentials with this code.

 ```
const login = useGoogleLogin({
    onSuccess: async (res) => {
      const { data } = await axios(
        "https://www.googleapis.com/oauth2/v3/userinfo",
        {
          headers: {
            Authorization: `Bearer ${res?.access_token}`,
          },
        }
      );
      console.log(data);
    },
  });
```

**Comment by TranTruongMinhThang** [comment]
@theviralboy I am sorry for my silly question, where can I put your code to run :( 
I want to use Calendar API but I can not get refresh token, I can use default google button to login and I stuck, could you help me out of this , thank you so much

**Comment by theviralboy** [comment]
> @theviralboy I am sorry for my silly question, where can I put your code to run :( I want to use Calendar API but I can not get refresh token, I can use default google button to login and I stuck, could you help me out of this , thank you so much

I think it's a separate issue. I am also not getting the refresh token.
