### ISSUE TITLE
Padding on containers??

### ISSUE THREAD

**Issue by ScottEAdams** [MomenSherif/react-oauth#108]
Any ideas why this extra padding is being added? Its the same on both the button and the prompt.
<img width="277" alt="image" src="https://user-images.githubusercontent.com/624154/197421669-494ac53e-5f5d-49fb-9999-a98919d136e4.png">

<img width="480" alt="image" src="https://user-images.githubusercontent.com/624154/197421707-385cac03-778e-47d8-b8b7-8b343710bb75.png">

**Comment by MomenSherif** [comment]
They are rendered by google within iframe

**Comment by ScottEAdams** [comment]
I thought so. Find it really weird that it could look like this out of the box.

**Comment by trybick** [comment]
Does anyone know a workaround to override the classes to remove the extra space?

**Comment by MomenSherif** [comment]
Try adding color-scheme css property with the theme you are using idk of that will fix it or not

https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme

**Comment by trybick** [comment]
Thanks for the suggestion. Tried adding some global CSS with color-scheme but didn't seem to work. Ended up using the `react-google-button` for a custom button (in conjunction with this library)
