### ISSUE TITLE
Getting user information from successful authentication

### ISSUE THREAD

**Issue by trungbui2000** [MomenSherif/react-oauth#109]
Hi all,

I would like to ask if it is possible me to get user information after they have successfully authenticated themselves. The information that I am looking for is:
- Email address
- First and last name
- Profile picture (if any)

If there is a way, I would really appreciate it if anyone can give me the right pointer as to where I can find additional information regarding this issue. Thanks in advance!

**Comment by philippechevieux** [comment]
@behind24proxies Are you sur about that ?

I only got an object like this : 
`{
    "clientId": "xxxxxxxxx.apps.googleusercontent.com",
    "credential": "xxxxxxxxxxx",
    "select_by": "btn"
}`

**Comment by philippechevieux** [comment]
Anwser here : https://github.com/MomenSherif/react-oauth/issues/105#issuecomment-1287676742

**Comment by trungbui2000** [comment]
@philippechevieux thank you!!!
