### ISSUE TITLE
how do I use the auth code from useGoogleLogin  ?

### ISSUE THREAD

**Issue by behind24proxies** [MomenSherif/react-oauth#110]
I tried using 
GoogleLogin 
it works and it returns a jwt with all the data that I need 
but I have to use the button provided by google , in other words I have to use useGoogleLogin ; the problem with this is that it returns tokens weird lookin' tokens
so , is there a way to access the email of the user given these tokens ?

**Comment by behind24proxies** [comment]
hi, it turns out that I have to add 
https://www.googleapis.com/auth/userinfo.email
to the scopes , but I cannot pass any scopes to `useGoogleLogin`  , any solutions ?

**Comment by behind24proxies** [comment]
ok, fixed it, turns out that you need to send a get request to 
https://www.googleapis.com/oauth2/v3/userinfo?access_token=implicit_bearer_token
something that is not written in the docs

**Comment by theoradicella** [comment]
Hey @behind24proxies  can you explayate on this? I'm having the same issue, you get back a response with a field called "credential" when I send this to verificate with oAuth I get an invalid token response..

**Comment by behind24proxies** [comment]
well, are you using the default google button? 
(this)
```
import { GoogleLogin } from '@react-oauth/google';

<GoogleLogin
  onSuccess={credentialResponse => {
    console.log(credentialResponse);
  }}
  onError={() => {
    console.log('Login Failed');
  }}
/>;
```
or are you trying to use a custom button ?

**Comment by TranTruongMinhThang** [comment]
Hello @behind24proxies , could you help me with this step. I am so new in here, and try to learn to use Calendar API with this tutorial: 
[https://www.youtube.com/watch?v=c2b2yUNWFzI&t](url)
but now we have to use this package to replace react-google-login.

Now, I stuck to figure out how to use 'useGoogleLogin' to get the refresh token.

1. Do I do right when create custom button like this:
`import React from "react";
import GoogleCalenderAPI from "./GoogleCalenderAPI";
import { useGoogleLogin } from '@react-oauth/google';

function App() {
    const login = useGoogleLogin({
       onSuccess: codeResponse => console.log(codeResponse),
       flow: 'auth-code',
    });

    return (
    <div>
        <GoogleCalenderAPI 
            onClick={() => login()}
        />
    </div>
    );
}
export default App;`

but I can not get any thing in console :(

Thank you for your help.

**Comment by behind24proxies** [comment]
@TranTruongMinhThang  
it looks like you don't understand that {GoogleLogin} and {useGoogleLogin} are 2 different things
GoogleLogin -> a button that returns a jwt with the email , name and other useful info
useGoogleLogin -> hook that onsuccess returns an access token , you have to send this access token to the backend and send a request to the google oauth api to get the email address and name of the user

GoogleLogin must be used alone , useGoogleLogin + <div>/<button> + backend/frontend request to oauth api = GoogleLogin

in your example you are using them both.
you don't have to use usegooglelogin , just use GoogleLogin 
(It took me about 4 hours to figure out the difference between usegooglelogin  and google login , trying to save u some time )

this should be enough , test it and lmk

```jsx
export default function App() {
    return(
        <GoogleOAuthProvider clientId="891270123895-ceelnc6r1sjrqo2ik1te4rkl11ph3hnt.apps.googleusercontent.com">
        <GoogleLogin
            onSuccess={credentialResponse => {
                console.log("here: ")
                console.log(credentialResponse);
            }}
            onError={() => {
                 console.log('Login Failed');
            }}
            
        />
        </GoogleOAuthProvider>
    )   
}
```

**Comment by diogo-SG** [comment]
Thanks a lot @behind24proxies for figuring this out and posting it here! Just wanted to share this video I found on this subject which helped me finish this implementation on a project I'm working on: https://www.youtube.com/watch?v=TqlVP_IkS28

Hope it helps anyone else who needs it :)

**Comment by TranTruongMinhThang** [comment]
@behind24proxies thank you for replying me. 
and yes, I am confuse with them {useGoogleLogin} and {GoogleLogin}, so I am sorry to ask silly question :D After your explaination, I seem learn a lot, Thank you so much
I try GoogleLogin and it works but the data in jwt is not enough, I need refresh token to use with Google Calendar API - so 
 I think I have to use useGoogleLogin with prop is scope and use with this API, but yes, I dont understand how to do it :(
 
 and Thank you @diogo-SG for your video, I see you make it work with custom button {useGoogleLogin} - I will try your tutorial. basically, you dont use call back function like document - you just use `onClick = {login}` maybe that why I stuck - I will try tomorrow with scope also and hope to get refresh token. I am sorry for lacking of knowledge about this javascript, react, nodejs backend and ask some stupid question like this.

Thank you all, have a nice day!

**Comment by TranTruongMinhThang** [comment]
so sad, I try to follow the video of @diogo-SG but I can not make it work, what wrong with my code - I feel so hopeless now :(

```
import React from "react";
import Header from "./Header";
import Footer from "./Footer";
import GoogleCalenderAPI from "./GoogleCalenderAPI";
import { useGoogleLogin } from '@react-oauth/google';
import axios from "axios";
import GoogleButton from 'react-google-button'
import { GoogleOAuthProvider } from '@react-oauth/google';
// import GoogleCustomBtn from "./GoogleCustomBtn";

function App() {

    // const login = useGoogleLogin({
    //     onSuccess: async response => {
    //         try {
    //             const data = await axios.get(
    //                 'https://www.googleapis.com/oauth2/v3/userinfo', {
    //                 headers: {
    //                     "Authorization": `Bearer ${response.access_token}`
    //                 }
    //             })
    //             console.log(data);
    //         } catch (err) {
    //             console.log(err)
    //         }
    //     }
    // });
    return (
        <GoogleOAuthProvider clientId="891270123895-ceelnc6r1sjrqo2ik1te4rkl11ph3hnt.apps.googleusercontent.com">
        <GoogleButton
            // onClick={login}
        />
        </GoogleOAuthProvider>
    );
}
export default App;
```

**Comment by TranTruongMinhThang** [comment]
Ohm yeah, now I figure out the problem - I need to wrap <GoogleOAuthProvider> outside App in index.js and it will work 

this is index.js file
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './components/App'
import { GoogleOAuthProvider } from '@react-oauth/google';

ReactDOM.render(
        <GoogleOAuthProvider clientId="891270123895-ceelnc6r1sjrqo2ik1te4rkl11ph3hnt.apps.googleusercontent.com">
        <App />
        </GoogleOAuthProvider>
,
document.getElementById('root'));
```

**Comment by pguardiario** [comment]
> ok, fixed it, turns out that you need to send a get request to https://www.googleapis.com/oauth2/v3/userinfo?access_token=implicit_bearer_token something that is not written in the docs

Can you show how you did that? Do you have to pass the credential somehow?

**Comment by behind24proxies** [comment]
@pguardiario 
yes you have to pass the unique token 
like this
`https://www.googleapis.com/oauth2/v3/userinfo?access_token=REPLACE_THIS_WITH_UNIQUE_TOKEN_BRO`

**Comment by pguardiario** [comment]
No, I'm asking how do I get the access token. I have client id and
credential in the onSuccess callback.

**Comment by pguardiario** [comment]
useGoogleLogin gives me: {
    "code": "4/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "scope": "email profile openid https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email",
    "authuser": "0",
    "prompt": "consent"
}

and GoogleLogin gives me: {
    "clientId": "827xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
    "credential": "eyJhbGcixxxxlotsreally long string",
    "select_by": "btn"
}

I'm trying to find a way to use something like [googleapis](https://github.com/googleapis/google-api-nodejs-client#readme)  in a brower

**Comment by TranTruongMinhThang** [comment]
> useGoogleLogin gives me: { "code": "4/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "scope": "email profile openid https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email", "authuser": "0", "prompt": "consent" }
> 
> and GoogleLogin gives me: { "clientId": "827xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com", "credential": "eyJhbGcixxxxlotsreally long string", "select_by": "btn" }
> 
> I'm trying to find a way to use something like [googleapis](https://github.com/googleapis/google-api-nodejs-client#readme) in a brower

you can follow https://github.com/MomenSherif/react-oauth/issues/6 to get the token with backend

**Comment by MartynFitzgerald** [comment]
@pguardiario  Have a look at the different types of authentication code flows on Googles documentation 

https://developers.google.com/identity/protocols/oauth2#scenarios

**Comment by DigitalNaut** [comment]
Oh, man, I feel like all this needs to be clearly written somewhere in the README. It took me too many hours to realize that I now need to change my entire approach for the Access Token after getting my app to work with the GoogleLogin button component.

**Comment by PeterDimitroff** [comment]
> ok, fixed it, turns out that you need to send a get request to
> https://www.googleapis.com/oauth2/v3/userinfo?access_token=implicit_bearer_token
> something that is not written in the docs

Thank you for this. The Google Docs themselves couldn't be less helpful and convoluted, so you saved me.

I [created a PR ](https://github.com/MomenSherif/react-oauth/pull/128)to this repo adding this to the README.

**Comment by behind24proxies** [comment]
> > ok, fixed it, turns out that you need to send a get request to
> > https://www.googleapis.com/oauth2/v3/userinfo?access_token=implicit_bearer_token
> > something that is not written in the docs
> 
> Thank you for this. The Google Docs themselves couldn't be less helpful and convoluted, so you saved me.
> 
> I [created a PR ](https://github.com/MomenSherif/react-oauth/pull/128)to this repo adding this to the README.

it took me 5 hours to find that endpoint 
you're welcome

**Comment by eeshankeni** [comment]
Is it possible to get the Id token JWT instead of the access token?

**Comment by behind24proxies** [comment]
> Is it possible to get the Id token JWT instead of the access token?

Read this
https://github.com/MomenSherif/react-oauth/issues/110#issuecomment-1291844668
