### ISSUE TITLE
How can I get id_token?

### ISSUE THREAD

**Issue by Wqleonard** [MomenSherif/react-oauth#113]

**Comment by imaxisXD** [comment]
Hi in the credResponse you get the token id you can console log it and see 
see the screenshot for reference 
![image](https://user-images.githubusercontent.com/56172425/200026657-612f35cb-c0b2-432b-a018-b981c715e810.png)

**Comment by MomenSherif** [comment]
You can follow demo guide, https://react-oauth.vercel.app/
to choose which way you want to use the package and how to get user info
