### ISSUE TITLE
Render button when useGoogleLogin

### ISSUE THREAD

**Issue by meirarmon** [MomenSherif/react-oauth#114]
Hi,
Using the `GoogleLogin` component renders a button (as far as I can tell from the code, the button is rendered by the Google scripts).
I need to use the Authorazation flow, and as such I am using `useGoogleLogin`. My issue is that the example (as well as the code) seems to not support rendering a button, but I need to roll my own.
1. Is there an easy way to get a "standard" rendered button, so that I don't need to roll my own?
2. Is there a reason that when implementing the library it was implemented like this?
3. If there is an easy answer to (1), and there is no good answer to (2), would a PR that adds this feature be approved?
Thanks!

**Comment by MomenSherif** [comment]
Hello,
For authorization flows Google. Doesn't render any buttons via any script just give us a function to call to open the login process
And useGoogleLogin is just small wrapper around this
It's our own responsibility to create the button styles in any way you would like

**Comment by meirarmon** [comment]
Is there any library that you would recommend that renders the button in react? So that I don't need to deal with it?

**Comment by MomenSherif** [comment]
I would recommend styling it by yourself It would be easy and small in size

Or you can use something like this https://www.npmjs.com/package/react-social-login-buttons to render any social button you want

**Comment by meirarmon** [comment]
Thanks
