### ISSUE TITLE
Google auth not working in webview(instagram/messenger) App

### ISSUE THREAD

**Issue by siddhant-rigi** [MomenSherif/react-oauth#115]
When our users are trying to login through google by instagram/facebook webview they are getting error disallowed_useragent.

Somehow Leetcode/Pintrest and stackoverflow are doing this smoothly on instagram and facebook.
 

![Screenshot_20221024-133403](https://user-images.githubusercontent.com/89393592/198204466-41493f38-479d-49cf-96e1-5a640f48effa.png)

**Comment by MomenSherif** [comment]
I don't know how to fix it, But maybe you can check for the required google secure policy header they may require to make 3rd party apps work

**Comment by heekyu-pu** [comment]
same problem...
