### ISSUE TITLE
useGoogleLogin has hardcoded scopes that cannot be removed

### ISSUE THREAD

**Issue by CTVjweiss** [MomenSherif/react-oauth#124]
As currently implemented, if I want to ask for only a particular custom scope and I'm doing a custom login button using `useGoogleLogin()`, I can't do it. There are 3 hard-coded scopes on this line:
https://github.com/MomenSherif/react-oauth/blob/eb828709bd29a92a77bb8b513a0078604bc60303/packages/%40react-oauth/google/src/hooks/useGoogleLogin.ts#L90

I think it would be better if a scope is provided to use only that custom scope, not append it to a hard-coded list.

**Comment by MomenSherif** [comment]
These scopes will always be fetched even if they are not defined in scopes as I can remember (maybe I am wrong)

You can edit the package in node_modules in your project, and check the responses before and after the change

**Comment by CTVjweiss** [comment]
For my use case I only care about a user's YouTube data. Here's the auth screen with only `https://www.googleapis.com/auth/youtube.readonly` scope:

![image](https://user-images.githubusercontent.com/92741535/200021819-05fc2e98-5312-41c7-8e17-226a42a412c0.png)

Here it is with the full set of scopes if using this package:
![image](https://user-images.githubusercontent.com/92741535/200022170-b2424ae5-f4a2-4ebd-a3ee-0403f9f7a84a.png)

**Comment by Sherry40931** [comment]
I am facing a similar issue, have you found any workaround to solve it?

**Comment by CTVjweiss** [comment]
@Sherry40931 my current workaround is just copy-pasting the source code into my project and editing it to remove the hard-coded scopes. Once the issue is fixed I plan on switching to referencing this npm package instead.

**Comment by MomenSherif** [comment]
@CTVjweiss @Sherry40931 New version will be published tonight, Thanks for your suggestion!

**Comment by MomenSherif** [comment]
@CTVjweiss @Sherry40931 You can now pass `overrideScope: true`, with scope string to override default values

https://github.com/MomenSherif/react-oauth/releases/tag/%40react-oauth%2Fgoogle%400.5.0
