### ISSUE TITLE
Not working with gsuites emails

### ISSUE THREAD

**Issue by pguardiario** [MomenSherif/react-oauth#127]
Does anyone know what changes need to be made to get this working with non-gmail.com addresses (gsuites?)
I have it working for gmail.com emails with auth errors for the others

**Comment by MomenSherif** [comment]
I used it in production code with my company email and it was working, .....@company-name.com

**Comment by pguardiario** [comment]
I got it working with one out of 2 gsuites accounts. If I figure out the issue I will try to post it here
