### ISSUE TITLE
Q: Why the library does not redirect me?

### ISSUE THREAD

**Issue by naughtyfox** [MomenSherif/react-oauth#129]
Hi!

I'm trying to log in a user to my backend and for this purpose I have to follow `auth-code` flow. What confuses me is that official Google [doc](https://developers.google.com/identity/protocols/oauth2/web-server#httprest_1) says:

> redirect_uri: Determines where the API server redirects the user after the user completes the authorization flow. ....

I can successfully get auth code, but it doesn't matter if pass `redirect_uri` argument into `useGoogleLogin` hook or not, no redirect happens. 

Of course I can send the code to the backend by myself as many of my colleagues do, but I'd like to figure out why it happens this way.

Here is my code:

```
const Login = () => {
    const login = useGoogleLogin({
        redirect_uri: 'http://localhost:8000/auth/complete/google-oauth2/',
        flow: 'auth-code',
        onSuccess: (response) => {
            console.log(response)
        }
    })

    return (
            <GoogleLoginButton onClick={login}>Log in with Google</GoogleLoginButton>
    );
};
```

Is it something I'm doing wrong?

**Comment by GiacintoCarlucci** [comment]
Following as I have the same behaviour

**Comment by meetbeyond** [comment]
>         redirect_uri: 'http://localhost:8000/auth/complete/google-oauth2/',
I think you need to set ux_mode: 'redirect'

**Comment by MomenSherif** [comment]
Yea missing ux_mode: 'redirect'
