### ISSUE TITLE
Failing to resolve module 'react/jsx-runtime'

### ISSUE THREAD

**Issue by epresaskds** [MomenSherif/react-oauth#13]
Hello, I'm migrating from [@react-google-login](https://github.com/anthonyjgrove/react-google-login/issues/502) because the deprecation of old Google API, but I'm getting this error while building my app in local:

```
Failed to compile.

../node_modules/@react-oauth/google/dist/index.esm.js
Module not found: Can't resolve 'react/jsx-runtime' in 'path/to/my/project/node_modules/@react-oauth/google/dist'
```
I'm using the following versions:
```
"react": "16.10.2",
"react-dom": "16.10.2",
"typescript": "3.9.5",
"@react-oauth/google": "^0.2.1",
... rest of dependencies ommited for brevity
```

Thanks in advance!

Update: After realising that jsx-runtime is from react 17 (duh me), is there any way to make this library compatible with react 16?

**Comment by MomenSherif** [comment]
Hello @epresaskds, I'm sorry but the build output was targeting the new JSX transformation,  as you figured out.

I will give it a try today and will notify you

**Comment by epresaskds** [comment]
Perfect! it works like a charm, Thanks
