### ISSUE TITLE
How to get rid of this ugly padding in google one tap login?

### ISSUE THREAD

**Issue by ablaszkiewicz** [MomenSherif/react-oauth#138]
![image](https://user-images.githubusercontent.com/54682207/202870947-c2d9d62d-f19d-4530-ab39-33c4dfabc16a.png)

Anyone any tips on how to remove this ugly padding?

**Comment by spicybackend** [comment]
This is present on the Google sign in button with personal information as well, but it only displays with a white background in dark mode. In light mode the padding sits on a transparent background.

Unsure if it's an issue with the library or Google sign-in itself 🤔
