### ISSUE TITLE
Callback URL

### ISSUE THREAD

**Issue by enyelsequeira** [MomenSherif/react-oauth#139]
Hello, @MomenSherif 

This is not a bug, more of a feature I guess that I could not find. I have a google button that and it needs to handle a callback, using a redirect UI natively without any library I can get it to work, but does this lib support something like this? instead of a callback function pass a url link that's what the backend expects 
```jsx
 useEffect(() => {
    /* global google */

    window?.google.accounts.id.initialize({
      client_id:
        'personalClientID',
      ux_mode: 'redirect',
      login_uri: 'specificuri',
      callback: 'uricallback',
      nonce: getNonce().then((res) => res.data),
    });
    window.google.accounts.id.renderButton(
      document.getElementById('google-signin-button'),
      {
        theme: 'outline',
        size: 'large',
        longtitle: true,
        type: 'standard',
        text: 'sign_in_with',
        // data.callback
      }
    );
  }, []);

**Comment by MomenSherif** [comment]
Hello @enyelsequeira, 

Currently, it's not, callback function is the only supported way

I didn't try the callback url before, You can submit PR and a small example for nodejs backend to give it a try if possbile
