### ISSUE TITLE
Feature Request: Popup Dialog Closed Event/Error code

### ISSUE THREAD

**Issue by PeterDimitroff** [MomenSherif/react-oauth#142]
It would be very useful if a callback can be fired in case the user closes the Google Auth dialog.

This is needed for example for stopping any loaders/spinners.

[react-google-login used to have this](https://www.npmjs.com/package/react-google-login) within the `onFailure` event as an error code '`popup_closed_by_user`'

**Comment by MomenSherif** [comment]
Added onNonOAuthError now for @react-oauth/google@0.5.1, It's supported only for useGoogleLogin, as Google doesn't that for the implicit authentication

If you figured out a way to add it the personalized button, Submit your PR I will be happy to add it.
