### ISSUE TITLE
How to get id_token using useGoogleLogin Hook ? 

### ISSUE THREAD

**Issue by YuvantBesre** [MomenSherif/react-oauth#144]
It's a simple question yet there is no answer anywhere. Instead of closing this issue can you please straight forwardly answer how do we acquire id_token using useGoogleLogin hook ? 

1. The implicit flow returns an access_token 
2. The authorization flow returns a code. 

But how do I find out the id_token from one of the above ? 
I need to have an id_token since our backend is verifying the user using id_token only.

**Comment by MomenSherif** [comment]
To get id_token you can use GoogleLogin to get it directly

Or for the custom hook
You need to use auth-code flow which will return you an authorization code which can be exchanged by 
`access_token` `id_token` and `refresh_token` on the backend

If you are using nodejs for your backend, you can find backend example in demo link in README, if not you can find other languages on google docs

**Comment by LexisDev** [comment]
Is there any way to change design button with GoogleLogin?

**Comment by ssaprank** [comment]
@MomenSherif I have same problem as @YuvantBesre. Our backend expects id_token right away. At the same time - we are currently using a custom google sign in button.

 Are there any plans to allow getting the id_token also into the useGoogleLogin callback?

if not - would it be possible to allow customizing the GoogleLogin button? 

[this package](https://www.npmjs.com/package/react-google-login) allowed to do so. Are there any plans to also allow it in your package?
