### ISSUE TITLE
How to get a Refresh token when login

### ISSUE THREAD

**Issue by innovatorved** [MomenSherif/react-oauth#145]

**Comment by MomenSherif** [comment]
use authorization code flow using the custom hook, and exchange the code with the backend for 
`access_token` `id_token` and `refresh_token`

**Comment by mindell** [comment]
> use authorization code flow using the custom hook, and exchange the code with the backend for `access_token` `id_token` and `refresh_token`

I am using google-api-php-client on the backend trying to get the access_token and refresh_token, but I am always getting the `redirect_uri_mismatch` error when fetching access_token with the code. My supplied redirect_uri on the backend was registered as Authorized redirect URIs on the credential. Any idea what I am missing?

**Comment by MomenSherif** [comment]
In nodejs server I used 'postmessage' as string instead of redirect url parameter and it worked like that

**Comment by mindell** [comment]
> In nodejs server I used 'postmessage' as string instead of redirect url parameter and it worked like that
> 
> IDK of it will be the same for PHP

Thank you for your reply. I understand now that what I am doing will not work.

**Comment by innovatorved** [comment]
> use authorization code flow using the custom hook, and exchange the code with the backend for `access_token` `id_token` and `refresh_token`

My problem is solved i used the different approach after genrating refresh_token from oauthplayground

**Comment by laryhills** [comment]
How did you solve it?
