### ISSUE TITLE
Close login popup do nothing

### ISSUE THREAD

**Issue by Georgi-Filipov** [MomenSherif/react-oauth#146]
When I use useGoogleLogin or GoogleLogin it opens popup on click. After I logged it it do onSuccess action, but if I close the popup nothing happens. Can you maybe trigger "onFailure" error?

**Comment by MomenSherif** [comment]
Added onNonOAuthError now for @react-oauth/google@0.5.1, It's supported only for useGoogleLogin, as Google doesn't that for the implicit authentication

If you figured out a way to add it the personalized button, Submit your PR I will be happy to add it.
