### ISSUE TITLE
Automatic Sign-In not working (auto_select prop ignored)

### ISSUE THREAD

**Issue by hawkeye312** [MomenSherif/react-oauth#148]
Setting `auto_select` prop doesn't seem to be doing anything. I checked [the code](https://github.com/MomenSherif/react-oauth/blob/master/packages/%40react-oauth/google/src/GoogleLogin.tsx) and don't see `auto_select` being used at all.

Specifically, if I close browser and reopen app, it does not sign in automatically. Need to click Log In with Google button each time.

**Comment by BaDo2001** [comment]
I am having the same issue.

**Comment by MomenSherif** [comment]
I tried in incognito, it works well if you have one account and logged in with this account before

If multiple sessions for multiple accounts used to login for same website google doesn't fire auto_select

`auto_select` for `GoogleLogin` is passes through `...props`

**Comment by samdelong** [comment]
I'm still having this issue. Ideally this would still work if you had multiple Google Accounts. It doesn't even work between refreshes.

**Comment by samdelong** [comment]
@MomenSherif could you point me where auto_select is used in the code? I would like to make a pull request to implement / fix this feature. Thanks

**Comment by MomenSherif** [comment]
@samdelong https://github.com/MomenSherif/react-oauth/blob/master/packages/%40react-oauth/google/src/types/index.ts#L18

It's the type for GoogleLogin button and it's passed to it's props, feel free to update it in PR

**Comment by itamararjuan** [comment]
This is still an issue. the library works great but the `auto_select` is ignored for me as well. I'm running this with a couple of google accounts logged in to Google. but only 1 account has been signed for the application i'm logging into.
