### ISSUE TITLE
Refresh expired id token (JWT) on client using TokenClient.requestAccessToken()?

### ISSUE THREAD

**Issue by justinhrobbins** [MomenSherif/react-oauth#15]
Part of this was previously discussed in [Issue 9](https://github.com/MomenSherif/react-oauth/issues/9) which ended with the reasonable recommendation to use the  Authorization code flow and have the backend obtain access, refresh and id tokens.

However, I did find some new information regarding the possibility of refreshing the id token (JWT) on the client (React) side and thought it might make sense to create a new issue for this specific question... Thanks again @MomenSherif for your patience. 🥇 

Background:
Possibly a lot of folks interested in this new react-oath library have previously used the popular [react-google-login](https://github.com/anthonyjgrove/react-google-login) library.  JWT token expiration after 1 hour was an issue people also struggled with using the react-google-login as seen in numerous Github issues on the react-google-login project.

There's some confusion (at least for me) whether it is possible to refresh the id token (JWT) from the client without requiring both the client id and secret. I did find this Blog post which provides a solution using the deprecated gapi library: [Add Google Login to your React Apps in 10 mins](https://javascript.plainenglish.io/add-google-login-to-your-react-apps-in-10-mins-c45315c93db0).

As discussed in the blog post (and the [code in Github](https://github.com/Sivanesh-S/react-google-authentication/blob/master/src/utils/refreshToken.js)):
> This function checks for expires_in timestamp or our custom time (before the token expires) and calls **reloadAuthResponse** which is a util function provided by the library and it handles refresh_token and obtains new tokenId.

As far as I can tell, this reloadAuthResponse() function does get a new id token with new expiration date without requiring both the client id and secret on in React.

Google's [Migrate to Google Identity Services](https://developers.google.cn/identity/oauth2/web/guides/migration-to-gis) does mention replacing GoogleUser.reloadAuthResponse() with TokenClient.requestAccessToken() and states:
> Create a single reentrant function containing requestAccessToken(), call it when an access token is first needed, and later, after the existing token expires and Google API calls return a 401 Unauthorized status code response.

Do I understand correctly this may be a way using the new API to replace expired JWT tokens? Or is this specific to requesting new access tokens?

**Comment by MomenSherif** [comment]
TokenClient.requestAccessToken unfortunately it will not refresh the token, It will just open the dialog to login

They mention here to open the dialog again for users to authenticate and obtain new token

You can check useGoogleLogin implementation the return function is just a wrapper around this.

They did that to improve security
![image](https://user-images.githubusercontent.com/52167824/169363790-af97ede2-619e-4882-8684-b9ba2206d9eb.jpeg)

You can find all details here 

https://developers.google.com/identity/oauth2/web/guides/overview

**Comment by justinhrobbins** [comment]
Ah! Ok. Let's close this Issue. I have a feeling others will have the same question so hopefully this Issue will be helpful for them.
