### ISSUE TITLE
Not returning id_token or credential with Hook

### ISSUE THREAD

**Issue by abizden** [MomenSherif/react-oauth#151]
when I use normal <GoogleLogin> component, while cridential ie tokenid is returned in callback. Access_token is returned when I use the hook version to customize the button. What needs to be done to return credential in Hook version?

**Comment by zidanomar** [comment]
up~! same issue here

**Comment by alexfaber2011** [comment]
Perhaps https://github.com/MomenSherif/react-oauth/issues/144 will answer your question.

**Comment by ty-codes** [comment]
I've got the same issue. Currently using another library until this is resolved

**Comment by mamadfar** [comment]
guys, did you get all the user information with this package? I mean like name, email, imageUrl or anything like this.
I didn't get any useful info, just access_token and googleId

**Comment by aminekhalifa92** [comment]
same issue here

**Comment by zidanomar** [comment]
> guys, did you get all the user information with this package? I mean like name, email, imageUrl or anything like this.
> I didn't get any useful info, just access_token and googleId

I use the access_token and verify it with my backend and it will returns the user’s information. You can take a look at documentation [here](https://developers.google.com/identity/sign-in/web/backend-auth)

**Comment by vajajak** [comment]
We've been stuck on this issue for quite some time, then we discovered that you can obtain credentials object (which is the same thing as ID token in google's terminology) by calling:
`curl "https://oauth2.googleapis.com/tokeninfo?access_token=ACCESS_TOKEN"`.

Found in docs here: https://cloud.google.com/docs/authentication/token-types#access-contents

Hope this helps.

**Comment by paymog** [comment]
> We've been stuck on this issue for quite some time, then we discovered that you can obtain credentials object (which is the same thing as ID token in google's terminology) by calling: `curl "https://oauth2.googleapis.com/tokeninfo?access_token=ACCESS_TOKEN"`.
> 
> Found this purely by luck in Google Cloud docs here: https://cloud.google.com/docs/authentication/token-types#access-contents
> 
> (Of course, this could get implemented into the library, which would be great).
> 
> Hope this helps.

this is super helpful but [access tokens](https://cloud.google.com/docs/authentication/token-types#access) and [ID tokens](https://cloud.google.com/docs/authentication/token-types#id) are a bit different! 

I wish the docs made it easier to figure out how to exchange one for the other.

**Comment by paymog** [comment]
> > guys, did you get all the user information with this package? I mean like name, email, imageUrl or anything like this.
> > I didn't get any useful info, just access_token and googleId
> 
> I use the access_token and verify it with my backend and it will returns the user’s information. You can take a look at documentation [here](https://developers.google.com/identity/sign-in/web/backend-auth)

do you mind expanding on what you mean by `verify it with my backend`? How do you do that? Are you exchanging the access token for an ID token somehow?

**Comment by zidanomar** [comment]
> do you mind expanding on what you mean by `verify it with my backend`? How do you do that? Are you exchanging the access token for an ID token somehow?

basicaly, i verify the access_token to get user's information using [google-auth-library-nodejs](https://github.com/googleapis/google-auth-library-nodejs) from my backend. But I think you can do that from your frontend side using the same library also

I hope you got the idea, i totaly forgot what happend that time and why i did this since it has been a while

**Comment by paymog** [comment]
Figured out how to get user profile information using this library! Here's a message I've dropped in a few other issues, might as well drop it here too.

> For anyone who migrates to this library and wants to use it to get information about the user like their name and profile photo, you have to use the `userinfo` endpoint with the access token to get that info. Here's an axios request which will get all that info:
> 
> ```
>     const {data: {given_name, family_name, picture, email, email_verified}} = await axios.get("https://openidconnect.googleapis.com/v1/userinfo", {
>       params: {
>         access_token: access_token,
>       }
>     })
> ```
> 
> where `access_token` is a field on the value provided to the `onSuccess` callback.
