### ISSUE TITLE
Support for older browsers eg. chrome 45

### ISSUE THREAD

**Issue by jeremycy** [MomenSherif/react-oauth#153]
Hi there,  this is not an issue but a question - 

There seems to be es6 dept for this lib which could cause issue for older browsers -  any suggestion on alternative or what can be done to address this?  Fairly new to google oauth here.   

Thanks in advance and this has worked well so far,  except the compatibility requirement :(

**Comment by MomenSherif** [comment]
@jeremycy I'm sorry but Chrome 45 version is very old, and I wouldn't update the build to bundle to very old bundle

you can copy and paste the implementation from the source code and take it in your project directly
