### ISSUE TITLE
Google asks users to grant permission every time when a user is trying to authenticate App (useGoogleLogin hook + Authorization code flow)

### ISSUE THREAD

**Issue by uliboss** [MomenSherif/react-oauth#154]
Grreetings!
Thanks for implementing this lib. I implemented Custom google sign-in button using useGoogleLogin Hook with Authorization code flow. However, google asks users to grant permission every time when a user is trying to authenticate to my App. Even though the user already granted access and the scope didn't change. Is there a way to fix this?
Thanks!

**Comment by MomenSherif** [comment]
As the app is still not approved by google it will ask the user for permission every time

Once your app is approved from google side it will be fixed

**Comment by uliboss** [comment]
Hm, Im migrating from react-google-login lib => my App was already approved by Google.

Strange, but I managed to fixed it by removing old approved acceesses in my google account. However, I tested it only in development mode, not sure how it will behave in production

**Comment by uliboss** [comment]
I think this issue is on my side, thanks for response! Closing
