### ISSUE TITLE
{ ux_mode: "redirect" } is not working

### ISSUE THREAD

**Issue by Youssefgamer685** [MomenSherif/react-oauth#156]

**Comment by shaarangg** [comment]
For me it's redirecting it to the google auth but it's not letting me to select account it's defaulting to the default account logged in.
![image](https://user-images.githubusercontent.com/62327490/209545371-943cd93e-45ca-4061-bc98-405ac364cfca.png)
![image](https://user-images.githubusercontent.com/62327490/209545388-480f1a2c-fe84-4302-b3fe-d1e4d591c13a.png)

**Comment by Youssefgamer685** [comment]
> For me it's redirecting it to the google auth but it's not letting me to select account it's defaulting to the default account logged in. ![image](https://user-images.githubusercontent.com/62327490/209545371-943cd93e-45ca-4061-bc98-405ac364cfca.png) ![image](https://user-images.githubusercontent.com/62327490/209545388-480f1a2c-fe84-4302-b3fe-d1e4d591c13a.png)

Your Development Server Link is not match the link that you put in [clinet_id](https://console.cloud.google.com/apis/credentials), Maybe.

**Comment by Youssefgamer685** [comment]
> For me it's redirecting it to the google auth but it's not letting me to select account it's defaulting to the default account logged in. ![image](https://user-images.githubusercontent.com/62327490/209545371-943cd93e-45ca-4061-bc98-405ac364cfca.png) ![image](https://user-images.githubusercontent.com/62327490/209545388-480f1a2c-fe84-4302-b3fe-d1e4d591c13a.png)

Your Development Server Link is not match the link that you put in [clinet_id](https://console.cloud.google.com/apis/credentials), Maybe.

**Comment by shaarangg** [comment]
So I think it was a mistake on my part, I didn't understand the documentation properly. The redirect_uri should match the redirect_uri added in the google cloud project.

**Comment by meetbeyond** [comment]
Also there is no need for onSuccess callback as it doesn't get called anyway when using ux_mode redirect

**Comment by MomenSherif** [comment]
`ux_mode` redirect is only working with `flow` auth-code, it's limitation by google and you will find the authorization code in query params the onSuccess callback is not used in redirect mode
