### ISSUE TITLE
How to specify `response_type=code` for authentication?

### ISSUE THREAD

**Issue by kennym** [MomenSherif/react-oauth#157]
In the OAuth spec, there’s an option for requesting the provider return a code rather than a credential: https://www.oauth.com/oauth2-servers/server-side-apps/authorization-code/

I think this also applies to the Google API.

How can we specify a `response_type=code` using this client?

**Comment by kl-thamm** [comment]
With the new Google Identity the response type code is preserved for authorization, not for authentication. For authentication you now only get the ID-Token.

You can find the information here: https://developers.google.com/identity/authorization


To use the code flow for authorization see the following example:
https://github.com/MomenSherif/react-oauth#authorization-code-flow

**Comment by sp-luciano-chinke** [comment]
Is there a way to use the 'auth-code' flow with the default GoogleLogin button? I don't want to create a custom button, just want to use this kind of authorization.

**Comment by kl-thamm** [comment]
No, it is not how Google intends it. See:  https://developers.google.com/identity/
You should not use the auth-code flow for authentication, but for authorization. Therefore their library does not provide a login button for authorization.

**Comment by sp-luciano-chinke** [comment]
Thanks for you clarification!
