### ISSUE TITLE
Prevent the captcha challenge from triggering ?

### ISSUE THREAD

**Issue by vincentdurufle** [MomenSherif/react-oauth#158]
Hi,

I'm trying to test my website with playwright. The test is quite simple it logins with this library and redirects when the login is successful.
To test this I'm using a headless chromium browser. Now on my local machine I have no problem making it work but when installed on my remote server it is always asking for a captcha challenge which I cannot solve.
Is there any way to prevent this from happening at all by changing some settings on the component or is it something that cannot be bypassed from google ? 

Thanks in advance

**Comment by MomenSherif** [comment]
Hello,

I don't know how to turn it off,

But found some resources that might help to turnoff these 2fa challenges for login

https://support.google.com/a/thread/123796588/disable-captcha-image-selector?hl=en

https://support.google.com/a/thread/123796588/disable-captcha-image-selector?hl=en
