### ISSUE TITLE
I want to add a feature if you are okay with it

### ISSUE THREAD

**Issue by SmitharyZach** [MomenSherif/react-oauth#159]
Thoughts on adding a decode credential prop to the GoogleLogin component? This would decode the credential that gets passed back. I am doing this on my end 

                        onSuccess={(credentialResponse) => {
                            console.log(
                                jwt_decode(credentialResponse.credential)
                            );
                        }}

to get the decoded values like email etc. I am referencing this here: https://developers.google.com/identity/gsi/web/guides/handle-credential-responses-js-functions

Let me know, I'd love to add it! Awesome package by the way

**Comment by SmitharyZach** [comment]
@MomenSherif

**Comment by kl-thamm** [comment]
I don't see that to be within the scope of this library.
Just use common libraries like https://www.npmjs.com/package/jsonwebtoken

**Comment by jimcapel** [comment]
A lot of people (myself included) would want to send the jwt to a backend to decode & start a user session (and not decode on frontend).
