### ISSUE TITLE
Export type definitions

### ISSUE THREAD

**Issue by sebastian10c** [MomenSherif/react-oauth#16]
Hey, first of all thanks for all the effort put into this.
Would it be possible to export type definitions like for example `GoogleLoginProps`?

**Comment by MomenSherif** [comment]
Hello @sebastian10c , Sure it could be.

It will be added in the next version, maybe in 2 days.

I will notify you when it's released

**Comment by MomenSherif** [comment]
@sebastian10c Released https://github.com/MomenSherif/react-oauth/releases/tag/v0.2.3 🎉
