### ISSUE TITLE
OneTap reopening after login

### ISSUE THREAD

**Issue by kl-thamm** [MomenSherif/react-oauth#160]
After successful login using OneTap (or the regular sign in), the Google OneTap opens again when I reload the page and I am a bit clueless on how to debug it.
As no one else has complained about it, it is probably an implementation error on my end, but I cannot figure it out right now.

In App.tsx I wrapped my App with the provider:
```
  <GoogleOAuthProvider clientId={CONFIG.GOOGLE_CLIENT_ID}>
          <ProtectedApp />
    </GoogleOAuthProvider>
 ```
 
 I then have a Login-Component that send the ID-Token to my backend, verifies it and sends back a JWT.  The Login button is not displayed after login (so the Onetap-Hook cannot be called again for that reason as far as I am concerned).
 
 Do I have to persist the ID-Token or some cookie in the frontend? 
I thought it might be in GoogleOAuthProvider, but I couldnt find any state there.

**Comment by MomenSherif** [comment]
Yea, you need to keep persist and keep track of login state

**Comment by kl-thamm** [comment]
I do that of course! But is there anything specific to this library that I need to take care of?

**Comment by MomenSherif** [comment]
Nope,

Just don't render login button when user refreshes the page and be is already logged in

**Comment by kl-thamm** [comment]
Hm, that is what I do.
