### ISSUE TITLE
No auth_token from GoogleLogin, possible?

### ISSUE THREAD

**Issue by jtheberge** [MomenSherif/react-oauth#162]
Hey there, I haven't found an API example where it's possible to get auth_token from the GoogleLogin personalized button. I'm currently using it and only get id_token. Is it possible to get back auth_token too?

**Comment by MomenSherif** [comment]
Hello

Unfortunately google only provides the personalized button for implicit authentication

For authorization you will need to use the custom hook for implicit or code authorization flows
