### ISSUE TITLE
Refresh token?

### ISSUE THREAD

**Issue by maxouzeer** [MomenSherif/react-oauth#163]
Hello! I undetstand fom the Google Docs (https://developers.google.com/sheets/api/quickstart/nodejs) that wen user goes through the auth flow, we should receive an access token AND a refresh token. However, This is what I get from tokenResponse (only access_token):

`access_token
: 
"yaXXxxxXXXxxxXXXxxxXXXxxxxXXxxxXx"
authuser
: 
"0"
expires_in
: 
3599
prompt
: 
"none"
scope
: 
"email profile https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive openid"
token_type
: 
"Bearer"`

Am I missing something? How can I get refresh token in order to perform actions on behalf of my users later on? Thanks!

**Comment by maxouzeer** [comment]
Ok I found the way. To get a refresh token, we need to run the "auth-code" flow to get a code than we'll then exchange against access_token and refresh_token.

`import { useGoogleLogin } from '@react-oauth/google';

const login = useGoogleLogin({
  onSuccess: codeResponse => console.log(codeResponse),
  flow: 'auth-code',
});

<MyCustomButton onClick={() => login()}>
  Sign in with Google 🚀{' '}
</MyCustomButton>;`

**Comment by akashks1998** [comment]
Is there a way to get a refresh token using `GoogleLogin` instead of a custom button?

**Comment by maxouzeer** [comment]
@akashks1998 as far as I understand from @MomenSherif , no it's not
