### ISSUE TITLE
Pre-select the scope with useGoogleLogin

### ISSUE THREAD

**Issue by maddionatoplus** [MomenSherif/react-oauth#164]
Is it possible to pre-select (or make them mandatory) the scopes specified in the hook: 

`
const googleLogin = useGoogleLogin({scope: "...", onSuccess: () =>{} }, flow: "auth_code") 
`

**Comment by MomenSherif** [comment]
No we can't make them mandatory, google doesn't provide that option


But you can check for accepted scopes to alert the user if missing some of them

**Comment by maddionatoplus** [comment]
I've found some services that does this, using the same scopes that I use. 
Here is an example:

<img width="504" alt="Screenshot 2023-01-20 at 12 19 03" src="https://user-images.githubusercontent.com/81677826/213683744-3cf91b13-b57f-4d27-9341-d43f3cc18ed3.png">

Then I found that hasGrantedAllScope(tokenResponse, "...") doesn't work with the onSuccess callback of useGoogleLogin (the type is different)

![image](https://user-images.githubusercontent.com/81677826/213684032-76f729eb-4d88-421d-9d1b-98beb4e5dcc2.png)

**Comment by MomenSherif** [comment]
As I can remember token response has scopes property with accepted scopes

Try to log token response too see what inside it,
If it has accepted scopes you can compare them with your scopes manually

**Comment by milmih** [comment]
Try using `overrideScope: true` in the `useGoogleLogin` config, maybe that'll solve your issues. 🤷
