### ISSUE TITLE
 The given origin is not allowed for the given client ID.

### ISSUE THREAD

**Issue by vikas-viki** [MomenSherif/react-oauth#165]
why this is coming, I have added http://localhost:3000 in authorized origin and I am using react app

**Comment by UhMarco** [comment]
Have you added `http://localhost` as well as `http://localhost:<port_number>`? Have you configured your [oauth consent screen](https://console.developers.google.com/apis/credentials/consent)?

**Comment by vikas-viki** [comment]
yes that (http://localhost) was thing which I was missing, now got solved. thankyou for response☺.
