### ISSUE TITLE
Some scopes are not checked by default

### ISSUE THREAD

**Issue by UhMarco** [MomenSherif/react-oauth#166]
I'm using...
```typescript
  const googleLogin = useGoogleLogin({
    scope: 'https://mail.google.com/ profile email',
    onSuccess: async ({ code }) => {
      const response = await axios.post('http://localhost:3001/auth/google', {
        code,
      });
      console.log(response);
    },
    flow: 'auth-code',
  });
  ```
...to achieve the following:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/52924494/213718615-4e13fa97-4045-4cf8-a003-a497bd98ab18.png">

If i add `overrideScope: true` and have only the gmail scope, it's checked but if I have multiple it is not checked by default. Is there anyway to make it so that it is? or even better not give the, the option, they should be able to either accept or cancel as my app won't work without this scope enabled.

Apologies if this is the wrong way to go about asking.

**Comment by MomenSherif** [comment]
User need to check them manually

You can check for the accepted scopes in the response of successful login to validate that all scopes are accepted
