### ISSUE TITLE
useGoogleLogin Hook doesn't work's after build react app into django

### ISSUE THREAD

**Issue by ofir-tan** [MomenSherif/react-oauth#167]
Hey guys, I have an issue with 'useGoogleLogin' Hook doesn't work's after build react app into django.
When I using react app on port 3000 and backend django on p8000 every thing work's, but after I build
react app and using port 8000, after I try to log in via google, I don't get any response at all - no error just nothing.

EDIT: I get the errors:
Failed to load resource: the server responded with a status of 400 
m=credential_button_library:45 [GSI_LOGGER]: The given origin is not allowed for the given client ID.

but the giving origin are allowed, so whats the problem?

Does anyone know the problem or give me a direction for the investigation?
Thanks!

**Comment by MomenSherif** [comment]
I think you need to update your google console to enable port 8000 as well

**Comment by eakenbor** [comment]
@ofir-tan where you able tto solve this?
