### ISSUE TITLE
Problem with hosted_domain

### ISSUE THREAD

**Issue by stslle** [MomenSherif/react-oauth#168]
Hi guys, there is a problem when I try to set hosted_domain. 
Click on the Google button new page is opened but the URL is incorrect and the page doesn't exist.

`		
<GoogleLogin
	size="large"
	type="filled_blue" 
	width="320"
	onSuccess={credentialResponse => {
		console.log(credentialResponse); 
	}}
	onError={(error) => {
		console.log(error); 
	}}
	hosted_domain="xyz.com"
/>
`

library version:  0.6.0

**Comment by nhatvu148** [comment]
I also have this same issue for the popup window when setting a specific hosted_domain:
![image](https://user-images.githubusercontent.com/54697578/215275566-a3489045-153d-46a7-ae3a-675b91cc47ee.png)
It looks like the page was redirecting too many times which caused the error.
Do you guys have any solutions?

**Comment by MomenSherif** [comment]
I tried it with my internal company-hosted domain and it's working well,

please double check your `hosted_domain` value
