### ISSUE TITLE
Neither onSuccess nor onError are not called when using hook

### ISSUE THREAD

**Issue by vincentsartoko** [MomenSherif/react-oauth#17]
When I clicked the button, it successfuly show the popup, however it doesn't do anything after logging in (onSuccess/onError not fired). Here is the code:

```
const handleGoogleLogin = useGoogleLogin({
    onSuccess: (res) => console.log(res),
    onError: (res) => console.log(res),
    flow: 'auth-code'
});
```

Everything works in development, but not in a production website.

**Comment by MomenSherif** [comment]
I tried it, and it's working

you can check console here https://test-oauth-rust.vercel.app/

and this was my code

```jsx
  const login = useGoogleLogin({
    onSuccess: resp => console.log(resp),
    flow: 'auth-code',
  });

  return <button onClick={() => login()}>Login</button>;
```

please make sure your production URL is added in client id (Authorised JavaScript origins)

**Comment by vincentsartoko** [comment]
Here is the example, it would be nice if you can try on my website https://lahelu.com

1. click the login
![image](https://user-images.githubusercontent.com/56718724/169699317-8ba8421a-c25d-429e-be6a-0acc1be9f00c.png)

2. sign-in by Google
![image](https://user-images.githubusercontent.com/56718724/169699330-fdf8421b-5d1d-4899-a108-98fad484f626.png)

**Comment by MomenSherif** [comment]
@vincentsartoko I really don't know why.

I recommend you copy the implementation of the package to your `GoogleOAuthProvider`  and its dependencies and `useGoogleLogin` and try to debug callback returned by google.


I tried to reproduce the issue. But couldn't, If your project on public repo give me link I will try to support

**Comment by vincentsartoko** [comment]
I have tried it and no response was given too, currently I am running the website under Nginx, do you think this is one of the reason why my oauth doesn't work? Everything works in localhost...

```
const client = (_a = window.google) === null || _a === void 0 ? void 0 : _a.accounts.oauth2[clientMethod]({
  client_id: clientId,
  scope: `openid profile email ${scope}`,
  callback: (response) => {
    console.log(response); // Not returning anything
    var _a, _b;
    if (response.error)
      return (_a = onErrorRef.current) === null || _a === void 0 ? void 0 : _a.call(onErrorRef, response);
    (_b = onSuccessRef.current) === null || _b === void 0 ? void 0 : _b.call(onSuccessRef, response);
  },
  ...props,
});
```
