### ISSUE TITLE
Issue with react-oauth package when using it in chrome extension

### ISSUE THREAD

**Issue by smeetagrawal** [MomenSherif/react-oauth#170]
- Hi, I have implemented this package in my project and its working fine in website, but when I am trying to use in chrome extension, its showing me below error.

![image](https://user-images.githubusercontent.com/21281748/215065997-d1790bda-502e-434a-a4ac-8145967e3960.png)

And below is the manifest.json file which I am using.

{
  "short_name": "test",
  "name": "test",
  "description": "the bestestest extension chrome has",
  "version": "1.0",
  "manifest_version": 3,
  "action": {
      "default_popup": "index.html",
      "default_title": "Open the popup"      
  },
  "icons": {
      "16": "favicon.ico",
      "32": "favicon.ico",
      "48": "favicon.ico",
      "128": "favicon.ico"
  },
  "start_url": ".",
  "display": "standalone",
  "theme_color": "#000000",
  "background_color": "#ffffff"
}

I have searched for this issue and found that chrome extension is not allowing external scripts to load, I have tried some solutions by adding content_security_policy in manifest.json, but not able to fix this issue.

Can you please provide some solution for it @MomenSherif

**Comment by MomenSherif** [comment]
@smeetagrawal Hello, unfortunately I don't have the time to search and make the package to be compatible with chrome extension.
Feel free to submit PR if you found a solution

**Comment by ddeisadze** [comment]
@smeetagrawal so I went went step further. You can use this component in sandbox mode with background scripts by specifying this in the manifest file:

```
"sandbox": {
        "pages": [
            "login.html"
        ]
    },
    "content_security_policy": {
        "sandbox": "sandbox allow-scripts allow-forms allow-popups allow-modals; script-src 'self' *.google.com/*; script-src-elem https://accounts.google.com/gsi/client"
    },
```

But now the issue is that the origin that google expects is wrong :/ Do you know how to fix that?

**Comment by smeetagrawal** [comment]
Hi, I have tried your solution by trying to add the 'content_security_policy' inside manifest.json file like below. But still I am getting the same error inside console which I mentioned above in the image.
```
{
  "short_name": "React App",
  "name": "Create React App Sample",
  "icons": {
    "16": "favicon-16x16.png",
    "32": "favicon-32x32.png",
    "48": "logo48.png",
    "128": "logo128.png"
  },
  "manifest_version": 3,
  "action": {
    "default_popup": "index.html",
    "default_title": "Open the popup"
  },
  "content_security_policy": {
    "sandbox": "sandbox allow-scripts allow-forms allow-popups allow-modals; script-src 'self' *.google.com/*; script-src-elem https://accounts.google.com/gsi/client"
  },
  "version": "1.0",
  "start_url": ".",
  "display": "standalone",
  "theme_color": "#000000",
  "background_color": "#ffffff"
}

```

**Comment by smeetagrawal** [comment]
@ddeisadze one solution which I am thinking of which can resolve this issue is, when I check the code which is used in this package. you are using this external link `https://accounts.google.com/gsi/client` which is making the problem, because after introducing of manifest.json v3 we cannot use external script due to security concerns (for chrome extension).

So, what we can do is we can download that external script code in minified version and put that in the package project and then reference that file instead of the external script, this is what I have done when I faced this issue and after that it was working fine for both web app and for chrome extension as well.

Please provide your point of view for this solution and if you feel this is the correct way to solve this issue, I can generate a PR for it.

**Comment by ddeisadze** [comment]
@smeetagrawal I solved it. I created a new popup modal (hosted on the same domain as the redirect url), launched from background scripts. I then set a cookie with that popup modal, read it from background script, set it to chrome storage.

**Comment by smeetagrawal** [comment]
@ddeisadze will you release above fix in upcoming release, please let me know when you are going to release it. So I can try it out. Thanks.

**Comment by bayramn** [comment]
Any update on this?

**Comment by SitrucL** [comment]
Hi @smeetagrawal was your suggestion/solution to **patch** the `@react-oauth/google` package after it's been installed or **fork** the package, modify it to use a `local minified` version of the script and then use that in my project?
