### ISSUE TITLE
Google Sign-In JavaScript platform library deprecation

### ISSUE THREAD

**Issue by JonaZach** [MomenSherif/react-oauth#171]
Hi all,

I have received an email regarding the Google Sign-In JavaScript platform library being deprecated after March 31st, 2023 and that I should migrate to Google Identity Services before this date in my web application (instead of legacy Google sign-in web solution).
I use this package (@react-oauth/google) and it works perfectly. I have looked in this package source code and it uses these lines of code that are also used in Google Identity Services:
window.google.accounts.id.initialize({…..})
window.google.accounts.id.renderButton({…..})

So why did I receive the email? What should I change in my code? 

Thank you in advance

**Comment by MomenSherif** [comment]
Hello,

Maybe your clientId was generated at the past so Google maybe was warning you to update for their new JS library.

No worries I guess.

**Comment by JonaZach** [comment]
@MomenSherif Thanks
