### ISSUE TITLE
Provide Logout Method

### ISSUE THREAD

**Issue by Aniket-lodh** [MomenSherif/react-oauth#173]
I believe `Goggle Logout` method should be implemented. So that by using that we can confirm the user has successfully logged out. But till now I have only encountered `googlelogout` void function which does not return anything.

In the Previous `react-oauth-login` package `GoogleLogout` method was provided. I wonder why in this new Oauth npm package the same method was not provided??

**Comment by MomenSherif** [comment]
Google now doesn't track user loggin state, we will need to track it ourselves with a state and persist it the way we want

the googlelogout exported method is only for a special case need to be called if you are using one tap login

**Comment by MohannedAlNouman** [comment]
Well how would we go about logging someone out?

**Comment by MomenSherif** [comment]
@MohannedAlNouman If you are storing the log-in state in your app, just set the user with null value when he logs out
if you are persisting it in cookies/localstorage remove it from there when user logs out

you don't need any extra functionality from google side, they don't track user log-in state
