### ISSUE TITLE
How do I fix it?

### ISSUE THREAD

**Issue by AmitElrom** [MomenSherif/react-oauth#174]
Uncaught 
xo
message
: 
"Missing required parameter client_id."
stack
: 
"Error: Missing required parameter client_id.\n    at new xo (https://accounts.google.com/gsi/client:224:59)\n    at yo (https://accounts.google.com/gsi/client:219:118)\n    at Mp.Ep (https://accounts.google.com/gsi/client:269:395)\n    at new Mp (https://accounts.google.com/gsi/client:273:424)\n    at Object.initTokenClient (https://accounts.google.com/gsi/client:277:565)\n    at http://localhost:3000/static/js/bundle.js:12469:110\n    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:70183:30)\n    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:71935:17)\n    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:71900:13)\n    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:71887:11)"
type
: 
"missing_required_parameter"
[[Prototype]]
: 
Error

**Comment by MomenSherif** [comment]
Make sure you are passing correct clientId for `<GoogleOAuthProvider />`

**Comment by meetbeyond** [comment]
Make sure to add clientId in the GoogleOAuthProvider wrapper.
