### ISSUE TITLE
useGoogleLogin - how to get access to user email

### ISSUE THREAD

**Issue by grzegorzCieslik95** [MomenSherif/react-oauth#175]
Hello i try to create my custom auth buttom and i use hook useGoogleLogin but i need reponse in credentialResponse type, can i transform tokenResponse to credential response?

Many thanks, 
Grzegorz

**Comment by MomenSherif** [comment]
Hi,

You can choose between implicit and code flow by passing flow property to the hook

**Comment by grzegorzCieslik95** [comment]
Hello thanks for your response. How can transform codeFlow or tokenFlow to get id_token and email?

**Comment by MomenSherif** [comment]
You can follow Authorization here will explain it to you

https://react-oauth.vercel.app/
