### ISSUE TITLE
How to generate nonce with state param using useGoogleLogin hook and auth_code flow?

### ISSUE THREAD

**Issue by MicahRamirez** [MomenSherif/react-oauth#176]
### Problem

I can only generate the nonce at mount time because if I update the state variable after mount the client has a stale state variable and I will always have a mismatch on the nonce I add to state. 

This seems like a problem because a bad actor can just check component state or LS ahead of the redirect.

The state param is not a part of the dependency array.
https://github.com/MomenSherif/react-oauth/blob/master/packages/%40react-oauth/google/src/hooks/useGoogleLogin.ts#L123

Could I open a PR for this or is there something I am doing wrong? If a more thorough example of the use case would be helpful I can provide it. Thanks!

**Comment by MomenSherif** [comment]
Yea sure, Feel free to open PR

I will check it once you fix the issue

**Comment by enyelsequeira** [comment]
hello @MicahRamirez how do you pass the nonce to the useGoogleLogin, I could not find an example of it or @MomenSherif

**Comment by MomenSherif** [comment]
Can be passed to GoogleOauthProvider as prop
