### ISSUE TITLE
Provider doens't unmount when push to a new route (nextjs 13).

### ISSUE THREAD

**Issue by UnArtisant** [MomenSherif/react-oauth#179]
When i try to change the internalization of the app with next router.push (ex : '/fr/login' -> '/en/login') 

The provider throw this : 

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

safelyCallDestroy
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (26374:0)
commitHookEffectListUnmount
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (26557:0)
commitHookPassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29052:0)
commitPassiveUnmountInsideDeletedTreeOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29256:0)
commitPassiveUnmountEffectsInsideOfDeletedTree_begin
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29208:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29070:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29131:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29098:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29131:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29131:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29131:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29131:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29131:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29098:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29131:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29098:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29098:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29098:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29098:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29098:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29131:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29131:0)
recursivelyTraversePassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29084:0)
commitPassiveUnmountOnFiber
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29131:0)
commitPassiveUnmountEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29013:0)
flushPassiveEffectsImpl
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (31738:0)
flushPassiveEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (31680:0)
commitRootImpl
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (31587:0)
commitRoot
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (31330:0)
performSyncWorkOnRoot
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (30406:0)
flushSyncCallbacks
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (14254:0)
flushPassiveEffectsImpl
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (31760:0)
flushPassiveEffects
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (31680:0)
eval
../../node_modules/.pnpm/next@13.1.6_vuxjv6o7qhupugnkyf7vyqsruq/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (31422:0)

**Comment by UnArtisant** [comment]
btw everything works just fine without the provider

**Comment by MomenSherif** [comment]
Weird,

Feel free to submit PR for the solution that can be compatible with react and next 13
