### ISSUE TITLE
How to get profile picture from credential GoogleLogin

### ISSUE THREAD

**Issue by aminekhalifa92** [MomenSherif/react-oauth#180]
i use GoogleLogin Btn and after the  login i decode response.credential to get user information  

`  const getJwt = async (jwtToken) => {
    const [, payload] = jwtToken.split('.')
    return JSON.parse(atob(payload))
  }`

- Result: 

`aud: "671XXXX"
azp: "67124XXX"
email: "amine.XXX"
email_verified: true
exp: 1675680457
family_name: "XXX"
given_name: "XXX"
hd: "XXX"
iat: 1675XXX
iss: "httXXX"
name: "AmiXXX"
nbf: 1675XX
sub: "11389XXX"`

But I can't find the props picture or imageUrl to get profile picture
version: "@react-oauth/google": "^0.6.0"
Thanks in advance

**Comment by MomenSherif** [comment]
It should return I tried it here in the playground with my account https://react-oauth.vercel.app/

IDK if google doesn't response with image for specific cases (like user doesn't allow that from google settings)

**Comment by cristianocasm** [comment]
@aminekhalifa92, FWIW I tested with 2 email accounts:

- First one being my personal email (ending in gmail.com)
- Second one being my professional email (ending in tutodigital.com.br)

When using the first one, payload brings no `hd` property but do brings `picture` property. When using the second one, the payload returns the `hd` property but no `picture` property.

`hd` stands for Hosted Domain. In my case, when `hd` is present, it is equal to `"tutodigital.com.br"`.

So my conclusion is that, by default, professional emails doesn't allow picture sharing(?) 🤷‍♂️ 

Try with a personal email and I suppose it'll work.

**Comment by paymog** [comment]
For anyone who migrates to this library and wants to use it to get information about the user like their name and profile photo, you have to use the `userinfo` endpoint with the access token to get that info. Here's an axios request which will get all that info:

```
    const {data: {given_name, family_name, picture, email, email_verified}} = await axios.get("https://openidconnect.googleapis.com/v1/userinfo", {
      params: {
        access_token: access_token,
      }
    })
```

where `access_token` is a field on the value provided to the `onSuccess` callback.
