### ISSUE TITLE
Please add a onRequest callback

### ISSUE THREAD

**Issue by zehawki** [MomenSherif/react-oauth#181]
Hello, thank you for this package. I'm migrating from react-google-login to this. 

For the useGoogleLogin hook, in addition to onSuccess and onError, please provide an onRequest prop. This is quite essential to know when the button has been clicked.

**Comment by MomenSherif** [comment]
Hello,

But you can do the logic that you want within onClick for your button before calling the login method

**Comment by zehawki** [comment]
Yes of course, just find that cleaner than this for instance:

```
      onClick={() => {
        props.onRequest()
        login();
      }} >
```
