### ISSUE TITLE
How can I hide oneTap command when I logged in?

### ISSUE THREAD

**Issue by DVHuan** [MomenSherif/react-oauth#182]
I use `useGoogleOneTapLogin` hook, so the oneTap command always display. When user logged in with other method (eg. Facebook), how can I hide oneTap command. Because `useGoogleOneTapLogin` is hook, therefore I cannot wrap it with `if, else`.
Thanks all.

**Comment by MomenSherif** [comment]
You can wrap it in a component and conditionally render the component

Or you can submit PR for enabled option flag for the hook
