### ISSUE TITLE
How do i get the id_token to send to my backend? i am only getting the access_token

### ISSUE THREAD

**Issue by Bernard-Namangala** [MomenSherif/react-oauth#183]

**Comment by ZitRos** [comment]
+1 this is beneficial. Google uses idToken (not access_token) for verification: https://developers.google.com/identity/sign-in/web/backend-auth

`useGoogleLogin` gives only access_token

<img width="199" alt="image" src="https://user-images.githubusercontent.com/4989256/219136002-d5a91cad-5527-4cd5-8876-2d610f526bf6.png">

**Comment by paymog** [comment]
For anyone who migrates to this library and wants to use it to get information about the user like their name and profile photo, you have to use the `userinfo` endpoint with the access token to get that info. Here's an axios request which will get all that info:

```
    const {data: {given_name, family_name, picture, email, email_verified}} = await axios.get("https://openidconnect.googleapis.com/v1/userinfo", {
      params: {
        access_token: access_token,
      }
    })
```

where `access_token` is a field on the value provided to the `onSuccess` callback.

**Comment by MomenSherif** [comment]
Please check the playground https://react-oauth.vercel.app/

you will find different ways how to get user info the way you will use the library

**Comment by acro5piano** [comment]
@paymog Thank you.

**Comment by elsemk** [comment]
Tested and available

`import React from 'react';
import GoogleIcon from '@/assets/common/google-icon.png';
import { useAsyncEffect, useMemoizedFn } from 'ahooks';
import { googleClientId } from '@/utils/global';

import { gapi, loadGapiInsideDOM } from 'gapi-script';

const Login = () => {
  useAsyncEffect(async () => {
    const gapi = await loadGapiInsideDOM();
    gapi.load('auth2', function () {
      gapi.auth2.init({
        client_id: googleClientId,
      });
    });
  }, []);

  const handleClickGoogle = useMemoizedFn(() => {
    const auth2 = gapi.auth2.getAuthInstance();
    auth2.signIn().then(function (googleUser: any) {
      const googleInfo = googleUser.getAuthResponse();
      console.log(googleInfo, '====');
      const id_token = googleInfo.id_token;
      if (id_token) {
        // todo
      }
    });
  });

  return (
    <div className="h-full overflow-x-hidden bg-[#E5B5E7] pt-[15%] relative max-w-450">
      <div
        className={'btn-primary flex-center-center'}
        onClick={handleClickGoogle}
      >
        <img width={24} height={24} className="mr-10" src={GoogleIcon} />
        Google
      </div>
    </div>
  );
};

export default Login;
`
