### ISSUE TITLE
How To Correctly Implement React GoogleOAuth

### ISSUE THREAD

**Issue by StevenServicePros239** [MomenSherif/react-oauth#184]
I am trying to implement the React GoogleOAuth. I currently have installed the @React-oauth/google library. When trying to import the GoogleLogin component from the library I am getting an parsing error from the console.

![image](https://user-images.githubusercontent.com/118549083/217903538-02a425cb-5743-4841-9fff-24c54f6225fc.png)

**Comment by MomenSherif** [comment]
Can you share with me your package.json deps

**Comment by StevenServicePros239** [comment]
"dependencies": {
    "@azure/msal-browser": "^2.18.0",
    "@emotion/core": "^10.0.14",
    "@emotion/styled": "^10.0.14",
    "@sentry/react": "^6.19.6",
    "@sentry/tracing": "^6.19.6",
    "autoprefixer": "^7.1.1",
    "babel-core": "^6.24.1",
    "babel-eslint": "^7.1.1",
    "babel-jest": "^15.0.0",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-polyfill": "^6.23.0",
    "babel-preset-env": "^1.5.1",
    "babel-preset-react": "^6.11.1",
    "cancan": "^3.0.0",
    "chunk-manifest-webpack-plugin": "^1.1.2",
    "classnames": "^2.2.5",
    "compression-webpack-plugin": "^1.0.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.2",
    "eslint": "3.19.0",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-import-resolver-webpack": "^0.8.3",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^4.0.0",
    "eslint-plugin-react": "^6.10.0",
    "expose-loader": "^0.7.3",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.1",
    "flexbox-react": "^4.4.0",
    "immutability-helper": "~2.0.0",
    "intro.js-react": "^0.3.0",
    "isomorphic-fetch": "^2.2.1",
    "jest": "^15.1.1",
    "js-yaml": "^3.8.4",
    "jsuri": "^1.3.1",
    "jwt-autorefresh": "^0.2.4",
    "jwt-decode": "^2.0.1",
    "lodash": "^4.13.1",
    "moment": "^2.22.2",
    "moment-business-days": "^1.0.6",
    "moment-range": "2.2.0",
    "mousetrap": "^1.6.1",
    "nock": "^8.0.0",
    "normalize.css": "^4.1.1",
    "normalizr": "^2.2.1",
    "path-complete-extname": "^0.1.0",
    "postcss": "^6.0.9",
    "postcss-cssnext": "^3.0.2",
    "postcss-loader": "^1.3.3",
    "postcss-smart-import": "^0.7.2",
    "precss": "^1.4.0",
    "prop-types": "^15.6.2",
    "qs": "^6.3.0",
    "rails-erb-loader": "^5.1.0",
    "react": "^16.0.0",
    "react-addons-css-transition-group": "^15.4.2",
    "react-addons-perf": "^15.4.2",
    "react-another-signature-pad": "^0.9.2",
    "react-confirm": "^0.1.14",
    "react-css-themr": "^2.1.0",
    "react-data-export": "^0.5.0",
    "react-dnd": "^2.1.4",
    "react-dnd-html5-backend": "^2.1.2",
    "react-dom": "^16.0.0",
    "react-dropzone": "^3.6.0",
    "react-google-login": "^5.0.0",
    "react-helmet": "^5.1.3",
    "react-hot-loader": "next",
    "react-infinite": "^0.12.1",
    "react-joyride": "^2.3.0",
    "react-redux": "^5.0.2",
    "react-responsive": "^1.1.3",
    "react-router": "^3.0.5",
    "react-router-redux": "^4.0.5",
    "react-router-scroll": "^0.4.1",
    "react-sanfona": "^0.2.3",
    "react-select": "^1.0.0-rc",
    "react-signature-canvas": "^1.0.1",
    "react-signature-pad": "^0.0.6",
    "react-tagsinput": "^3.13.6",
    "react-tap-event-plugin": "^1.0.0",
    "react-test-renderer": "^15.3.2",
    "react-toast-notifications": "^2.4.4",
    "react-toolbox": "^2.0.0-beta.12",
    "react-tooltip": "^3.2.1",
    "redbox-react": "^1.2.9",
    "redux": "^3.5.2",
    "redux-actions": "^0.12.0",
    "redux-auth-wrapper": "^2.0.2",
    "redux-devtools": "^3.3.2",
    "redux-thunk": "^2.1.0",
    "redux-ui": "^0.1.1",
    "remote-redux-devtools": "^0.5.16",
    "reselect": "^2.5.3",
    "resolve-url-loader": "^2.0.2",
    "rsvp": "^3.5.0",
    "sass": "^1.43.4",
    "sass-loader": "^7.2.0",
    "signature_pad": "^2.2.1",
    "sinon": "^1.17.4",
    "style-loader": "^0.18.1",
    "tableau-api-js": "^2.8.1",
    "tap-spec": "^4.1.1",
    "tape": "^4.6.0",
    "toolbox-loader": "0.0.3",
    "webpack": "^3.10.0",
    "webpack-manifest-plugin": "^1.1.0",
    "webpack-merge": "^4.1.0",
    "worker-loader": "^0.8.1",
    "xlsx": "^0.14.0"
  }

**Comment by MomenSherif** [comment]
Upgrade you react and react scripts versions to support hooks at least react 16.8

**Comment by StevenServicePros239** [comment]
We are currently using class based comps and their are a lot of method we are currently using that are now deprecated so upgrading would be a lot more extensive. Is there anything else that you would recommend?

**Comment by MomenSherif** [comment]
You can copy paste the implementation from the source code, and build your own component
