### ISSUE TITLE
Not returning id_token with custom button

### ISSUE THREAD

**Issue by eatfit-rohan** [MomenSherif/react-oauth#187]
Previously, we were using `react-google-login` with custom button and it was directly returning `access_token` and `id_token` which we were passing to our backend. 

Please clarify these 2 doubts for me:
1. If I go via the `sign-in` flow, we can directly get the `id_token` and pass it to the backend **BUT** we **cannot** have a custom button.

2. If I take the `auth-code` route, I **CAN** make a custom button however it will return a `code` which I will send to the backend to exchange for `access_token` and `id_token`. Essentially, I will have to write new API on the backend and I'll have to make 2 API calls to my backend, in first passing the `code` and then in second passing the `id_token`.

These are my only 2 option, right?

**Comment by MomenSherif** [comment]
You don't need to lass id_token for backend to verify 

Exchanging the code and checking for client id itself is an verify that is the code is valid

**Comment by paymog** [comment]
I was using `id_token` with a previous library and found that the access_token returned by this library can be exchanged for user info. Here's an axios request which will get all that info:

```
    const {data: {given_name, family_name, picture, email, email_verified}} = await axios.get("https://openidconnect.googleapis.com/v1/userinfo", {
      params: {
        access_token: access_token,
      }
    })
```

where `access_token` is a field on the value provided to the `onSuccess` callback.

**Comment by eatfit-rohan** [comment]
![ef](https://user-images.githubusercontent.com/79308999/220574977-dd2ea093-d136-4068-bd91-8b12d7ebbf01.gif)

Hi using the regular google button. Why is the button changing after a second (going from "continue with google" to "sign in as") as in the clip above?

**Comment by AdamPanag** [comment]
> You don't need to lass id_token for backend to verify 
> 
> Exchanging the code and checking for client id itself is an verify that is the code is valid

I have the same issue.

@MomenSherif how could I verify the user and fetch his data only with `code`? The only way I can find is with id_token through `verifyIdToken` funtion from `google-auth-library`.

**Comment by MomenSherif** [comment]
exchanging the code itself is a verification that the code is valid

I had playground but it's kinda random, but you will find the way to exchange the code to tokens

https://github.com/MomenSherif/google-oauth2-playground-server

**Comment by MomenSherif** [comment]
Please check the playground https://react-oauth.vercel.app/

you will find different ways how to get user info the way you will use the library
