### ISSUE TITLE
how to correctly fire the callback passed to onScriptLoadFailure

### ISSUE THREAD

**Issue by GoksuOkar** [MomenSherif/react-oauth#188]
Hi, 
I am trying to fire a function when there is an error loading the google auth provider. I followed the documentation and passed a simple console.log using onScriptLoadFailure. GSI-Logger logs an error and google is not loading but my custom function is not getting fired. Just want to prevent the app from building if there is an error with the google loading. Thank you.

code I'm using:
`      <GoogleOAuthProvider
            clientId={`${process.env.REACT_APP_CLIENT_ID}`}
            auto_select
            onScriptLoadError={() => (console.log('error!'))}
      >
`

error I'm getting on console (I'm creating the error on purpose):

<img width="703" alt="Screen Shot 2023-02-16 at 1 44 23 PM" src="https://user-images.githubusercontent.com/95586617/219513236-cb03791b-fd40-491e-8c3b-08aabd7eb982.png">

**Comment by MomenSherif** [comment]
these error msg from google's GSI script the script loaded successfully but invalid client ID value
