### ISSUE TITLE
Google Oauth opens new tab on mobile and doesn't autoclose after success

### ISSUE THREAD

**Issue by paymog** [MomenSherif/react-oauth#189]
I just implemented Google Oauth like so:

```
export const OAuth = ({ setErrors, signup, handleLoginHookResult, next }) => {
  const [loginWithGoogleMutationHook] = useMutation(LOGIN_WITH_GOOGLE);
  const router = useRouter();

  const googleOauthSuccess = async (response) => {
    const { data, errors } = await loginWithGoogleMutationHook({
      variables: { token: response.access_token },
    });
    handleLoginHookResult(data?.loginWithGoogle, errors);
  };
  const googleOauthFailure = (response) => {
    console.log('google oauth failure', response);
    setErrors(JSON.stringify(response));
  };

  const googleLogin = useGoogleLogin({
    onSuccess: googleOauthSuccess,
    onError: googleOauthFailure,
  });

  return (
    <div className="my-4">
      <button
        className="bg-red-500 text-white w-full px-3 py-2 rounded mb-2 hover:bg-red-600 transition"
        onClick={() => {
          // TODO add support for webviews
          googleLogin();
        }}
      >
        <i className="fab fa-google mr-1" /> {signup ? 'Signup' : 'Login'} with Google
      </button>
    </div>
  );
};
```

This works extremely well on desktop.

However, I'm finding that on mobile this opens a new tab where the oauth successfully authenticates. But then this new tab stays open with a spinner

![image](https://user-images.githubusercontent.com/1986950/219693377-807b123c-64d4-497e-ba68-3f290c72bc4c.png)

while the tab which invoked the google oauth flow successfully logs in:

![image](https://user-images.githubusercontent.com/1986950/219693601-9449290c-b061-43d9-bf12-17c5cb5adcc2.png)

note that my profile photo is displayed in the app and that the tab for accounts.google.com is still open.

Is there some configuration I can use to auto-close the google auth tab on mobile after success/failure?

**Comment by paymog** [comment]
Oh, the tab auto-closes with safari on mobile but not with brave, even with shields turned off.

**Comment by MomenSherif** [comment]
IDK issue with brave, but it's related to google SDK, 

feel free to submit PR if you found a solution to add to the package
