### ISSUE TITLE
Redirect URI not being respected

### ISSUE THREAD

**Issue by paymog** [MomenSherif/react-oauth#190]
I'm trying to use `redirect-uri` with the `useGoogleLogin` hook but it's not being respected.

Here's my hook example:

```
  const googleLogin = useGoogleLogin({
    onSuccess: googleOauthSuccess,
    onError: googleOauthFailure,
    ux_mode: 'redirect',
    redirect_uri: 'http://localhost:3000'
  });
```

Here's the button which triggers the hook on click:

```
      <button
        className="bg-red-500 text-white w-full px-3 py-2 rounded mb-2 hover:bg-red-600 transition"
        onClick={() => {
          // TODO add support for webviews
          googleLogin();
        }}
      >
        <i className="fab fa-google mr-1" /> {signup ? 'Signup' : 'Login'} with Google
      </button>
```

Here's my redirect URIs in Google

![image](https://user-images.githubusercontent.com/1986950/219696757-29e983fe-3009-468f-9ec7-f26f31fb4c5c.png)

However, when I try to do a redirect flow on localhost, I see the popup UX get triggered.

<img width="888" alt="image" src="https://user-images.githubusercontent.com/1986950/219696979-311c6f8f-a324-4151-a1a1-0c334a7e182f.png">

How can I use the redirect flow?

**Comment by mruiz42** [comment]
I am experiencing this same issue. Seems that it will redirect the page to whatever page it was previously on without any callbacks being executed.

**Comment by MomenSherif** [comment]
`ux_mode` redirect is only working with `flow` auth-code, it's limitation by google and you will find the authorization code in query params the onSuccess callback is not used in redirect mode
