### ISSUE TITLE
Window.google.accounts is undefined

### ISSUE THREAD

**Issue by jimcapel** [MomenSherif/react-oauth#192]
Hi,

On initial app render, window.google.accounts is populated. However, when i navigate to a different page in my app and then use the back button in the browser. window.google.accounts is undefined.

Not sure why this is, any help would be appreciated ! (happy to post code if needed)

Thanks

**Comment by MomenSherif** [comment]
Hello,

Yea if you can repopulate the issue in codesandbox or public repo to troubleshoot that would help

**Comment by jimcapel** [comment]
Hi! thanks for your quick response :) I've actually just figured out its to do with using both your library and @react-google-maps/api at the same time, I think the load scripts might be inter-fearing with each-other.

So i'll get to the bottom of it, but thank you again for your quick response.

On a side note, when this issue was happening i was getting crashes due to accounts.id being undefined and your library not handling the error, i've fixed this locally (which lead me to realise my original issue is not with your library), however, i could raise a pr for you to take a look at ? just to stop these crashes in the future.

Thanks!

**Comment by MomenSherif** [comment]
Yea cool, go ahead

**Comment by alexeenko-frontend** [comment]
@jimcapel Hello!
I faced the same problem, how you solved it?
