### ISSUE TITLE
Writing tests with implicit flow

### ISSUE THREAD

**Issue by kiriarf** [MomenSherif/react-oauth#195]
Hi,

I am trying to write some jest tests for my custom button. I have implemented it in accordance with documentation and it works fine when testing manually in browser. However, I am running a lot of logic on top of it and need to test whether everything is working correctly.

### Code

```
<Button
      onClick={() => googleLogin()}
  >
      Continue with Google
  </Button>
```

```
const googleLogin = useGoogleLogin({
        onSuccess: tokenResponse => {
            onSign(tokenResponse)
        },
        onError: errorResponse => {
            handleError(errorResponse)
        }
    })
```

### Test

```
jest.mock('@react-oauth/google', () => ({
    ...jest.requireActual('@react-oauth/google'),
    useGoogleLogin: jest.fn(() => ({
        onSuccess: jest.fn(),
        onError: jest.fn()
    }))
}))
```

```
it('calls googleLogin when button is clicked', async () => {
        const isSignup = true

        const {
            renderer: { container }
        } = renderWithRelay(isSignup)
    
        const button = screen.getByText(/continue with google/i)
    
        fireEvent.click(button)
    
        await waitFor(() => {
          expect(useGoogleLogin).toHaveBeenCalled()
        })
    })
```

The button is rendered correctly, but I am getting the following error: `TypeError: googleLogin is not a function`
This makes sense, because useGoogleLogin is a hook, but I am not able to change anything inside the `onClick` without breaking it. Is there a way to mock it properly?

**Comment by MomenSherif** [comment]
Hello, useGoogleLogin mock function should return login function not object with onSuccess & onError these are the parameters of the hook not the return

**Comment by kiriarf** [comment]
Thanks very much for a prompt response, could you pls clarify what would the login function be in this case? Is it the onSign function that gets called on success? My end goal is to investigate what happens inside that function.

**Comment by MomenSherif** [comment]
You can check the source code implementation for the hook

But it just calls a method on google client created inside the hook

Best way to test this to make sure that google logins correctly is e2ed
