### ISSUE TITLE
useGoogleLogin always get exception "Google OAuth components must be used within GoogleOAuthProvider"

### ISSUE THREAD

**Issue by ada-powerful** [MomenSherif/react-oauth#198]
I have an issue on using useGoogleLogin to define a custom login button. It always pop out error:

Unexpected Application Error!
Google OAuth components must be used within GoogleOAuthProvider
Error: Google OAuth components must be used within GoogleOAuthProvider
    at useGoogleOAuth (https://localhost:3000/static/js/bundle.js:125684:11)
    at useGoogleLogin (https://localhost:3000/static/js/bundle.js:125793:7)

```
export default function YoutubeConnector(props) { 

    const login = useGoogleLogin({
        onSuccess: tokenResponse => 
            console.log(tokenResponse)
    });

    return (
        <GoogleOAuthProvider clientId='xxxxxxxx'>
            <Button onClick={login} />
        </GoogleOAuthProvider>
    );
}
```

**Comment by MomenSherif** [comment]
The hook use itself needs to be inside the Provider

Create custom component and use the hook and the button inside

**Comment by ada-powerful** [comment]
> The hook use itself needs to be inside the Provider
> 
> Create custom component and use the hook and the button inside

Got it! Tried to wrap the component and it worked, thanks!

**Comment by zob360** [comment]
not working
