### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 ()

### ISSUE THREAD

**Issue by Redchar1992** [MomenSherif/react-oauth#204]
I have already set my Credentials, but website report: Failed to load resource: the server responded with a status of 403 ()

**Comment by MomenSherif** [comment]
can you double check google console for the used clientId and allowed origin to use this clientId

**Comment by Redchar1992** [comment]
Resolved, can't take port number.

**Comment by angelxmoreno** [comment]
@Redchar1992 could you elaborate what you mean by "can't take port number" ? I am having the same issue.

**Comment by angelxmoreno** [comment]
nvm. found clarity in https://github.com/MomenSherif/react-oauth/issues/79#issuecomment-1225870736

for those that land here see the link if you are having the same issue
