### ISSUE TITLE
Get user's email address in auth-code flow

### ISSUE THREAD

**Issue by harrysun2006** [MomenSherif/react-oauth#205]
The library is awesome. I've successfully get the code through the CodeResponse in a auth-code flow. I'm just wondering is there a way to tell which email address that user entered or selected during the oauth? In current response, it only gives me something like: "authuser":"6".

**Comment by vastolf** [comment]
@harrysun2006 I'm not sure how this is accomplished via the `auth-code` flow, but if you use the `implicit` flow & have access to the `auth_token`, you can send a GET request to: https://www.googleapis.com/oauth2/v3/userinfo

You need to pass the `auth_token` as the `Authorization` header (as a Bearer token). 

```
var myHeaders = new Headers();
myHeaders.append("Authorization", "Bearer ya27.aXXXXXXXXXXXXXXXXpjK_APXIT1p2GdydvHw1Kb3h8szjRCXbTiI4kka9fllcHg-o27_c0J5RUIqYFLZEpXXXXXXXXXXXXXXXXXXXXRMgH75cvdKAF8EkDVznhaA7AXXXXXXXXXXXXXXXXXXXGbdwaIX0_7H7m3dNS2tni2zow-pw0166");

var requestOptions = {
  method: 'GET',
  headers: myHeaders,
  redirect: 'follow'
};

fetch("https://www.googleapis.com/oauth2/v3/userinfo", requestOptions)
  .then(response => response.text())
  .then(result => console.log(result))
  .catch(error => console.log('error', error));
```

**Comment by MomenSherif** [comment]
@harrysun2006 You will need to exchange the authorization code via backend, it will result in three tokens one of them is `id_token` which is jwt containes user info you can decode to get them

**Comment by KasunSKarunasekara** [comment]
Decode the token, there you can find the email, and subject (Google account ID)

**Comment by harrysun2006** [comment]
Thank you guys. I will make changes in backend implementation to make the email address optional and decode the email address out of the token when it's not passed from the frontend.
