### ISSUE TITLE
Seemingly no way to get id_token via implicit flow + non-useGoogleLogin components are broken

### ISSUE THREAD

**Issue by vastolf** [MomenSherif/react-oauth#206]
Is there no way to get the `id_token` via the implicit flow (custom button)?

Many people are moving from older GAuth libraries that return both the `id_token` and the `auth_token`, and backend functionality depends on it.

How can I can get an `id_token` utilizing the implicit flow?

Also, auth-code flow seems broken. When I use the useGoogleLogin hook with implicit flow, I am able to get back a proper response with an `auth_token`. However, if I try to switch it to use auth-code flow, I get a 400 error.

Further, when trying to use the `GoogleLogin` component (which is auth-code flow), I also get a 400 error, even though I've changed nothing about my context wrapper / client id.

**Comment by MomenSherif** [comment]
the built in `GoogleLogin` is not wrapper for auth-code flow hook, it's just a wrapper for google seamless signin

if you need authorization using the hook will be required, and getting user info will depend on your choice `implicit` or `auth-code` flows

you can follow the demo https://react-oauth.vercel.app/ to know the way to get user info for each method
