### ISSUE TITLE
Using in environments other than localhost

### ISSUE THREAD

**Issue by myungsangBaek** [MomenSherif/react-oauth#207]
Hello, I got a [GSI_LOGGER]: The given origin is not allowed for the given client ID. Error

I'm already regist  URL and redirect url in google console.

ex)
http://example.com
http://example.com:80

It's not https it's http 

No matter what method I try, it keeps giving me an error

Is it can't use on domain env?

**Comment by MomenSherif** [comment]
Hello,

http is allowed only for localhost
