### ISSUE TITLE
How to verify granted scopes with requested scopes in ux_mode: redirect

### ISSUE THREAD

**Issue by aksingh-jft** [MomenSherif/react-oauth#208]
I am using the below configuration : 

const login = useGoogleLogin({
    onError,
    flow: 'auth-code',
    ux_mode: "redirect",
    scope: globalConstants.GOOGLE_OAUTH_SCOPE,
    redirect_uri: globalConstants.OAUTH_REDIRECT_URL,
  });

After user gives the consent, user is redirected to the redirect url with the scope and auth-code appended in the url. How can I verify all the scopes are granted by the user and if all the scopes are not granted then how can I re-request for the scope that is not granted by the user.

**Comment by MomenSherif** [comment]
I don't remember if the accepted scopes also get passed in URL or not,

but for pop-up you can do something like that to check for your required scopes, 

```tsx
onSuccess: async ({ code, scope }) => {
      const acceptedScopes = new Set(scope.split(" "));
      const hasAcceptedAll = requiredScopes.every(s => acceptedScopes.has(s));

      if (!hasAcceptedAll) {
        return setError("Please accept all permissions required!");
      }

      setError(null);
      onLogin(code);
    },
```

if scopes not passed as query params in redirect mode, I think you can add this validation through backend while exchanging the code
