### ISSUE TITLE
Any ways to not have this displayed ?

### ISSUE THREAD

**Issue by ManuTadaa** [MomenSherif/react-oauth#211]
Hi every time the button is  rendered it is first with "Sign in with Google" and then change to this:

<img width="546" alt="Screenshot 2023-02-28 at 17 16 01" src="https://user-images.githubusercontent.com/112983722/221915058-c3add88c-92b9-4ee6-aea8-183964fddeb4.png">

I thought it was the auto_select option but setting it to false does not change a  thing.

Any  advice  ? Thanks!!

**Comment by MomenSherif** [comment]
If your browser has connected account to google it will show like that

**Comment by ManuTadaa** [comment]
Okk thanks!
