### ISSUE TITLE
When used Logout it is not loggin out the user from the google

### ISSUE THREAD

**Issue by RGLxAkuma** [MomenSherif/react-oauth#214]
The logout method simply logs out user in frontend but not from the google and the token generated during login is still accesible and valid even after using logout

**Comment by MomenSherif** [comment]
I think you will need to revoke the access token 
https://developers.google.com/identity/oauth2/web/reference/js-reference#google.accounts.oauth2.revoke

**Comment by RGLxAkuma** [comment]
are you planning to add this functionality to this package when we log out?

**Comment by RGLxAkuma** [comment]
> I think you will need to revoke the access token https://developers.google.com/identity/oauth2/web/reference/js-reference#google.accounts.oauth2.revoke

it is giving me error of "Invalid Token"

**Comment by MomenSherif** [comment]
Are you using the component? or the hook

**Comment by MomenSherif** [comment]
Try this

https://developers.google.com/identity/gsi/web/guides/revoke
The previous one for invoking access_token

**Comment by RGLxAkuma** [comment]
> Try this
> 
> https://developers.google.com/identity/gsi/web/guides/revoke The previous one for invoking access_token

how to use this in the web app , do i have to add any scripts in index.html??
