### ISSUE TITLE
[GSI_LOGGER]: The given origin is not allowed for the given client ID.

### ISSUE THREAD

**Issue by Ykyki4** [MomenSherif/react-oauth#215]
Hi, im trying to add google login to my react app, and i receive this error every time:

> Failed to load resource: the server responded with a status of 400 ()
> [GSI_LOGGER]: The given origin is not allowed for the given client ID.

Im running the site on django, port 8000, frontend is writed on react, using webpack. 

I setuped all like in the tutorial, added both of the urls, and it still not working. 

![Снимок экрана (64)](https://user-images.githubusercontent.com/105967328/223198696-09cb9a12-e251-465f-966a-f1964145cfa5.png)

Can i receive some help please?

**Comment by MomenSherif** [comment]
Hello,

use the same port as the react app is using

**Comment by Ykyki4** [comment]
> Hello,
> 
> use the same port as the react app is using

Im not using react app to launch the site, django is running, on the port 8000, i dont have any other running ports.

**Comment by MomenSherif** [comment]
The package is meant to be used inside react apps,

if you need the native js implementation you can check google docs, or copy-paste from the package source code what works for you

**Comment by Ykyki4** [comment]
Okay, thanks for the answer
