### ISSUE TITLE
redirect_uri not used while in ux_mode: 'popup'

### ISSUE THREAD

**Issue by crileyy** [MomenSherif/react-oauth#216]
Hi, I am having the same issue as this comment https://github.com/MomenSherif/react-oauth/issues/71#issuecomment-1350661948. Is it possible to honor a redirect_uri while in ux_mode: 'popup'?

**Comment by MomenSherif** [comment]
You can't mix with popup mode and the redirection uri

redirect_uri mode is working only with authorization code flow

**Comment by crileyy** [comment]
Ok thank you
