### ISSUE TITLE
redirect url on mobile

### ISSUE THREAD

**Issue by caushcani** [MomenSherif/react-oauth#219]
Hi, 
I'm using useGoogleLogin, implicit flow, and this is what's happening when I try to login from mobile.
Block code of what I have done:
 ```
const login = useGoogleLogin({
    flow: "implicit",
    onSuccess: async (googleRes: any) => {
      const userInfo = await axios.get('https://www.googleapis.com/oauth2/v3/userinfo', {
        headers: {
          Authorization: `Bearer ${googleRes.access_token}`
        }
      })
      handleGoogleResponse(userInfo.data);
    },
  });
```
When I open it from mobile, it opens a new window.

![WhatsApp Image 2023-03-08 at 11 34 12](https://user-images.githubusercontent.com/75629280/223690560-2ecd334d-2edf-4a2b-add1-1454ce5f0978.jpeg)

**Comment by MomenSherif** [comment]
hello redirect uri works only with authorization code flow

**Comment by MomenSherif** [comment]
is it working on your descktop?

**Comment by caushcani** [comment]
> is it working on your desktop?

yes, the problem was in project setup from google. thank u :)
