### ISSUE TITLE
useGoogleLogin to refresh the access token

### ISSUE THREAD

**Issue by saramenoncin** [MomenSherif/react-oauth#220]
Hi, first of all, thank you for your work!

I'm trying to use the implicit flow with `useGoogleLogin` hook in order to automatically refresh the user's access token.

Below the code so far

```
const updateUserInContext = async (response: any) => {
        const user = new User()
        user.accessToken = response.access_token
        user.isUserLoggedIn = true
        setCurrentUser(user) //this comes from a React context
    
        setTimeout(() => {
            loginWithCurrentUser()
        }, 50 * 60 * 1000)
    } 

    let loginWithCurrentUser = useGoogleLogin({
        onSuccess: (codeResponse: any) => {
            updateUserInContext(codeResponse)
        },
        onError: error => {
            console.log("error in with current user")
        },
        hint: 'user@example.com',
        prompt:'none'
    })

    const login = useGoogleLogin({
        onSuccess: async codeResponse => {
            updateUserInContext(codeResponse).then(() =>{
               //do other things
            }).catch(error => {
               console.log("error")
            })
        }, 
        onError: error => {
            console.log("error")
        },
        flow:'implicit'
    });
      
    return (
        <div>
            <button onClick={() => login()}>
                    Sign in with Google 🚀{' '}
            </button>
        </div>
    )
```

This approach is working as far as in the current browser there is only 1 google user logged in, or if `hint` user is exactly the one that logged in the app.

My question is: how can I make the `hint` prop variable based on the user that logged in?

Thank you!

**Comment by saramenoncin** [comment]
To achieve what I wanted, I had to do
```
        setTimeout(() => {
            loginWithCurrentUser({hint: email})
        }, 50 * 60 * 1000)
```

**Comment by ricardo-jsd-santos** [comment]
Hi, I'm currently struggling with the same issues, that is, making 'hint' dynamic.

@saramenoncin I'm trying your solution but, following the code you have,  `loginWithCurrentUser` will not take any parameters. Could you add its definition as you intended for it to be used in your snippet?

```javascript
setTimeout(() => {
    loginWithCurrentUser({hint: email})
}, 50 * 60 * 1000)
```

**Comment by saramenoncin** [comment]
I didn't change the definition of the `loginWithCurrentUser`.
I only removed the `hint` prop when defining the function, like this:

```
    let loginWithCurrentUser = useGoogleLogin({
        onSuccess: (codeResponse: any) => {
            updateUserInContext(codeResponse)
        },
        onError: error => {
            console.log("error in with current user")
        },
        prompt:'none'
    })
```

**Comment by ricardo-jsd-santos** [comment]
I see, thank you, @saramenoncin. As it turns out, my case was slightly different, possibly because I'm using 'auth-code' so my equivalent of your loginWithCurrentUser does not take the additional `hint` parameter when called.
