### ISSUE TITLE
 ux_mode and redirect_uri not working on useGoogleLogin

### ISSUE THREAD

**Issue by razh-lendlord** [MomenSherif/react-oauth#224]
The `ux_mode` and `redirect_uri` options are not working as expected with the useGoogleLogin hook. Despite setting `ux_mode` to 'redirect' and `redirect_uri` to a callback URL, the sign-in process still opens a popup window instead of redirecting the user to the specified URL in the current window. Here is an example of how I am using the useGoogleLogin hook:

```
const signIn = useGoogleLogin({
  uxMode: 'redirect',
  redirectUri: callbackURL
});
```

I have tried various options and checked the documentation, but the issue persists.

**Comment by MomenSherif** [comment]
Redirect mode works only with authorization code flow
