### ISSUE TITLE
One-tap sign-up

### ISSUE THREAD

**Issue by mzrybbd** [MomenSherif/react-oauth#225]
import { GoogleLogin } from '@react-oauth/google';

<GoogleLogin
  onSuccess={credentialResponse => {
    console.log(credentialResponse);
  }}
  onError={() => {
    console.log('Login Failed');
  }}
  useOneTap
/>

**Comment by mzrybbd** [comment]
![image](https://user-images.githubusercontent.com/33386828/224942252-45fd15d5-8f3e-4e1f-8cb3-bbb61cd1c4c9.png)
Use the upper code to add the left part

**Comment by bdada23** [comment]
what is the bug here? that is not auto-logging in?

**Comment by mzrybbd** [comment]
Should only render the top right corner？

**Comment by mzrybbd** [comment]
Can Sign in With Google button and One Tap be displayed on the same page
