### ISSUE TITLE
GSI Inline Style causing CSP violations

### ISSUE THREAD

**Issue by danfsd** [MomenSherif/react-oauth#229]
Hi, I'm implementing a strict set of Content Security Policies on my app and I found out that the GSI script creates an inline style that violates my `script-src` directive.

One of the ways to fix that would be to pass a nonce to the inline style.

I've [looked it up](https://stackoverflow.com/a/74525283/4830674) and it looks like we can get the nonce into the inline style by passing it to the GSI script tag.

**Comment by danfsd** [comment]
Tested and it worked. I don't think this addition has any implications or side-effects for the functioning of the library.

**Comment by MomenSherif** [comment]
Published, Thank you for your PR!
