### ISSUE TITLE
Origins with and without ports

### ISSUE THREAD

**Issue by gusaiani** [MomenSherif/react-oauth#23]
Hello @MomenSherif,

regarding this part of the installation instructions:

```
Key Point: Add both http://localhost and http://localhost:<port_number> to the Authorized JavaScript origins box for local tests or development.
```

Do you know why we need to add `http://localhost` when we will use a certain port locally?
Is this something on the lib side, or is this at another layer?

Just curious, as it's been a [source of difficulty in manual testing](https://github.com/metabase/metabase/pull/22868#pullrequestreview-992512876).

Thank you!

**Comment by MomenSherif** [comment]
Hello @gusaiani,

I know it seems weird, as localhost with port should be enough, and adding extra localhost seems to be redundant.

But it is google's recommendation for local tests or development.

you can find it in setup step 2 https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid

I would recommend following them, If you want to give it a try add only the one with port and try if it's working or not.

**Comment by gusaiani** [comment]
Thank you @MomenSherif.

It does not work in our tests without the portless domain, if we use a declared port.
Grateful to get the reference link above from you.
Likely we will add it to the instructions for our own users.
