### ISSUE TITLE
Possible to use `GoogleLogin` button for `useGoogleLogin` with scopes?

### ISSUE THREAD

**Issue by Infinitay** [MomenSherif/react-oauth#24]
I noticed `GoogleLogin` doesn't have a prop for scope, but `useGoogleLogin` does. Is it possible for me to use `GoogleLogin` components button but with either specifying a prop or overloading the onClick to use `useGoogleLogin` instead?

**Comment by MomenSherif** [comment]
Google's new service identity SDK, split their logic in two categories 
1. Sign-in flows ( simple authentication using `personalized button` or `oneTap` without have the ability to define scopes )
2. Authorization ( to be able to define scopes to call google APIs with `access_token`)

https://developers.google.com/identity/gsi/web

these two flows are exported as
1. Sign-in flow (GoogleLogin)
2. Authorization (useGoogleLogin)

if you need to define scopes you can use `useGoogleLogin`

unfortunately you can't overload onClick for GoogleLogin as google injects the button programmatically in iframe
