### ISSUE TITLE
redirect_uri_mismatch when exchanging code in ux_mode: 'popup', flow: 'auth-code'

### ISSUE THREAD

**Issue by polyakov** [MomenSherif/react-oauth#252]
In adding google login I am running into redirect_uri_mismatch when using `ux_mode: 'popup'` and `flow: 'auth-code'`.  It works with with  `ux_mode: 'redirect'` and `flow: 'auth-code'`.  To take my server code out of the equation, I am using HTTP/REST and Postman to troubleshoot the exchange.

To launch the login, I am using a custom button and 
```   
    const googleLogin  = useGoogleLogin({
        onSuccess:  googleCodeResponseSuccess,
        flow: 'auth-code',
        ux_mode: 'popup'
    });
```

The exchange happens using post to `https://oauth2.googleapis.com/token`.  

This process fails when using `ux_mode: 'popup'`.  If I set a mode to `redirect` and provide 'redirect_uri` then the exchange works as expected. 

Since I am not providing a redirect_uri for the popup, what redirect_uri should I use in the exchange?  I am grateful for any advice on how this should work.

**Comment by MomenSherif** [comment]
<img width="835" alt="Screenshot 2023-04-19 at 1 12 14 PM" src="https://user-images.githubusercontent.com/52167824/233057617-d2f331d8-435b-4f40-b696-a286e3846164.png">

on your server use postmessage as redirect_uri

**Comment by polyakov** [comment]
Thank you!

**Comment by felipfr** [comment]
> <img alt="Screenshot 2023-04-19 at 1 12 14 PM" width="835" src="https://user-images.githubusercontent.com/52167824/233057617-d2f331d8-435b-4f40-b696-a286e3846164.png">
> 
> on your server use postmessage as redirect_uri

I was using the authorization code flow together with popup, but when I change to 'ux mode' redirect, I start to get redirection error mismatch.

What URL should I put in the backend? And on the frontend? I have the local development environment, HML and PRD, do I have to change the address for all of them?

**Comment by patissier-boulanger** [comment]
> <img alt="Screenshot 2023-04-19 at 1 12 14 PM" width="835" src="https://user-images.githubusercontent.com/52167824/233057617-d2f331d8-435b-4f40-b696-a286e3846164.png">
> 
> on your server use postmessage as redirect_uri

Thank you so much!

**Comment by patissier-boulanger** [comment]
> > <img alt="Screenshot 2023-04-19 at 1 12 14 PM" width="835" src="https://user-images.githubusercontent.com/52167824/233057617-d2f331d8-435b-4f40-b696-a286e3846164.png">
> > on your server use postmessage as redirect_uri
> 
> I was using the authorization code flow together with popup, but when I change to 'ux mode' redirect, I start to get redirection error mismatch.
> 
> What URL should I put in the backend? And on the frontend? I have the local development environment, HML and PRD, do I have to change the address for all of them?

Use 'postmessage' in front and back like this

```
//backend

    const client = new OAuth2Client({
      clientId: this.configService.get<string>('GOOGLE_OAUTH_CLIENT_ID'),
      clientSecret: this.configService.get<string>(
        'GOOGLE_OAUTH_CLIENT_SECRET',
      ),
      redirectUri: 'postmessage',
    });
    
    
 //frontend
   const login = useGoogleLogin({
    flow: 'auth-code',
    redirect_uri: 'postmessage',
    onSuccess: async (tokenResponse) => {
      console.log(tokenResponse);

      const response = await fetch(
        'http://localhost:3000/api/v1/auth/google/signIn',
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            code: tokenResponse.code,
          }),
        },
      );
      console.log(response);
    },
  });   
 ```
I only tested it locally, but I don't think there will be any problems in other environments. Because it worked even if I didn't add 'postmessage' uri in gcp
