### ISSUE TITLE
React 18 login with auth code flow not working.

### ISSUE THREAD

**Issue by adventuretocode** [MomenSherif/react-oauth#256]
`import { useGoogleLogin } from '@react-oauth/google';

const login = useGoogleLogin({
  onSuccess: codeResponse => console.log(codeResponse),
  flow: 'auth-code',
});

<MyCustomButton onClick={() => login()}>
  Sign in with Google 🚀{' '}
</MyCustomButton>;
`

Error 
`
caught Error: Google OAuth components must be used within GoogleOAuthProvider
    at useGoogleOAuth (@react-oauth_google.js?v=f7a627d3:56:11)
    at useGoogleLogin (@react-oauth_google.js?v=f7a627d3:133:50) 
u
`

when i am defined 

` <button onClick={() => useGoogleLogin({
    onSuccess: tokenResponse => console.log(" tokenResponse :- ",tokenResponse),
    onSuccess: tokenResponse => console.log(tokenResponse),
  })  }>Sign in with Google 🚀{' '}
            </button>
            
            `
Error
`caught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
S`

**Comment by MomenSherif** [comment]
Wrap your application with GoogleOAuthProvider component and provide client id

**Comment by adventuretocode** [comment]
complete code 

`
 <GoogleOAuthProvider clientId={CLIENT_ID}>
          
            <button onClick={() => useGoogleLogin({
    onSuccess: tokenResponse => console.log(" tokenResponse :- ",tokenResponse),
    onSuccess: tokenResponse => console.log(tokenResponse),
  })  }>Sign in with Google 🚀{' '}
            </button>

            <button onClick={() => googleLogout()}>
                Logout Google 🚀{' '}
            </button>

        </GoogleOAuthProvider>

`

Error for login : caught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
S

**Comment by MomenSherif** [comment]
Please take a look at docs
You need to call hooks inside a component and it will return to you a login function

Or you can follow any guide on youtube like

https://youtu.be/TqlVP_IkS28

**Comment by adventuretocode** [comment]
@MomenSherif  react 18 not working still. that video not help me.

**Comment by wesleyguirra** [comment]
Same for me, tested with NextJS and React 18

**Comment by MomenSherif** [comment]
if you are using new next server components, you will need to wrap the provider and button in 'use client' directive till I update it in the package

**Comment by MomenSherif** [comment]
Can you share with me a demo on codesandbox or repo to try

**Comment by wesleyguirra** [comment]
Shame on me, while writing the codesandbox demo, I see that I mistaken put an additional space at the end of the clientId on the `GoogleOAuthProvider` causing the onSuccess not being called, after removing the extra space from the string it worked.

**Comment by MomenSherif** [comment]
No worries 🙌🏻

**Comment by brianfinkelstein** [comment]
> Shame on me, while writing the codesandbox demo, I see that I mistaken put an additional space at the end of the clientId on the `GoogleOAuthProvider` causing the onSuccess not being called, after removing the extra space from the string it worked.

those hard to find typos are the most frustrating!

**Comment by azamatos** [comment]
I think issue should be closed

**Comment by nicksenap** [comment]
I had the same problem @adventuretocode 
and I solved it by wrapper the <App> with the GoogleOAuthProvider  (in main.tsx)
hope this help!
