### ISSUE TITLE
Encountering issues with @react-oauth/google 0.11.0 - given origin is not allowed

### ISSUE THREAD

**Issue by nalbert9** [MomenSherif/react-oauth#264]
Hi,

I am using your library in my Next.js project and encountered the error "[GSI_LOGGER]: The given origin is not allowed for the given client ID" even though my Authorized JavaScript origins are correctly set up. The console also logs a "Failed to load resource: the server responded with a status of 403 ()" error. 

Can you provide guidance or assistance in resolving this?
**"@react-oauth/google": "^0.11.0",**

```
import { GoogleOAuthProvider } from "@react-oauth/google";
import { GoogleLogin } from "@react-oauth/google";

<GoogleOAuthProvider clientId="CLIENT_ID.apps.googleusercontent.com">
<GoogleLogin
  onSuccess={credentialResponse => {
    console.log(credentialResponse);
  }}
  onError={() => {
    console.log('Login Failed');
  }}
  useOneTap
/>
</GoogleOAuthProvider>
```
Thank you

**Comment by MomenSherif** [comment]
Hi

Make sure you are using the right client id

And configure you google console to allow localhost one without port and define it again localhost with the prt you are using

**Comment by nalbert9** [comment]
Yes, I have the correct one.

Authorized JavaScript origins:
http://localhost:3000
http://localhost

Authorized redirect URIs:
http://localhost:3000/api/auth/callback/google

**Comment by MomenSherif** [comment]
Alright,

If you can provide codesanbox sample with the issue would be great, and will I will check later today
