### ISSUE TITLE
idToken on custom button with useGoogleLogin hook

### ISSUE THREAD

**Issue by melvinotieno** [MomenSherif/react-oauth#269]
I know this issue has been raised before but I did not find any of the solutions helpful for my use case. What I would like to to get the idToken, send it to my server, verify that token, create my own tokens (access_token and refresh_token) using jwt and use those for subsequent requests. I have found this to be possible when going through the google sign in documentation here (https://developers.google.com/identity/gsi/web/guides/use-one-tap-js-api)

**Comment by MomenSherif** [comment]
getting `id_token` direct only available via GoogleButton

otherwise you can follow https://github.com/MomenSherif/react-oauth/issues/12 it has a backend example to verify against without id token and you can create your own access token at this time

**Comment by melvinotieno** [comment]
Makes sense but I would still need to save the google user id to the database in order to associate it with future logins

**Comment by MomenSherif** [comment]
Make it against emails, emails are unique

**Comment by melvinotieno** [comment]
But then again, to get the email, I still need the idToken, no?

**Comment by MomenSherif** [comment]
You will decode the id token on the server (its jwt)

**Comment by taronaleksanian** [comment]
@MomenSherif could you kindly say, why id_token, is not available with the custom button, is there any security issue or something else?
