### ISSUE TITLE
Get more data on CredentialResponse

### ISSUE THREAD

**Issue by syahirdev** [MomenSherif/react-oauth#29]
Currently, GoogleLogin onSuccess props is returning CredentialResponse which only has clientId, credential, and select_by. Are there any methods I can use to get more information like user profile name or profile image on response, for example below image? Thank you in advance!
![image](https://user-images.githubusercontent.com/67471898/171797994-fa741ca9-721c-44df-af5b-47a3e5e25a98.png)

**Comment by MomenSherif** [comment]
Too get user info you can decode
`credential` (which is JWT token) using jwt-decode or any thing you like
