### ISSUE TITLE
Cross-Origin-Opener-Policy policy would block the window.closed call.

### ISSUE THREAD

**Issue by marklar21** [MomenSherif/react-oauth#295]
as soon as I call useGoogleLogin 2 errors of Cross-Origin-Opener-Policy policy would block the window.closed call. appear in the console.  The account listing still occurs normally...

These are the 2 outputs I see in my console:

client:273 Cross-Origin-Opener-Policy policy would block the window.closed call.
cq.A @ client:273
lc @ client:56
_.l.dispatchEvent @ client:55
_.Me.G @ client:125

client:273 Cross-Origin-Opener-Policy policy would block the window.closed call.
cq.A @ client:273
lc @ client:56
_.l.dispatchEvent @ client:55
_.Me.G @ client:125

**Comment by sophie-pan** [comment]
Any fix ? or workaround ?

**Comment by xiangfengsu** [comment]
I had the same problem

**Comment by sophie-pan** [comment]
Ended up using `redirect` instead of `popup`.

I had a issue when exchanging auth code with id_token.
See: https://github.com/MomenSherif/react-oauth/issues/12#issuecomment-1686488957

**Comment by kunalkhichi** [comment]
Getting the same errors in console. Any solutions to remove this errors?

**Comment by MarwanDebbiche** [comment]
Same issue, I would be interested in any solution as well!

**Comment by kunalkhichi** [comment]
you may be getting error because of this npm package - [react-google-login](https://www.npmjs.com/package/react-google-login)

I suggest using this instead - [@react-oauth/google](https://www.npmjs.com/package/@react-oauth/google)

Changing npm package fixed my issue.

**Comment by MarwanDebbiche** [comment]
> you may be getting error because of this npm package - [react-google-login](https://www.npmjs.com/package/react-google-login)
> 
> I suggest using this instead - [@react-oauth/google](https://www.npmjs.com/package/@react-oauth/google)
> 
> Changing npm package fixed my issue.

I am using [@react-oauth/google](https://www.npmjs.com/package/@react-oauth/google)

Everything seems to work as expected but I get this message when opening the chrome dev tools console

**Comment by evan-boissonnot** [comment]
I have got the issue here in localhost.

**Comment by anshg03** [comment]
@kunalkhichi can u share the frontend implementation of @react-oauth

**Comment by kunalkhichi** [comment]
@anshg03  I have created a common component so that will be confusing for you. You can directly check for its How to use steps. I also followed the same.
![image](https://github.com/MomenSherif/react-oauth/assets/126649779/2b9bd153-9d48-4931-a07f-0da787a26a19)

**Comment by MomenSherif** [comment]
For CSP added google's guide in the README

**Comment by mgoldenbe** [comment]
So, has anyone figured out what exactly we need to do to get rid of the error message in the Console when testing at localhost:3000?
