### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'oauth2')

### ISSUE THREAD

**Issue by omarwael98** [MomenSherif/react-oauth#297]
I am working on nextjs 13 app and I want to setup google signup but every time I use useGoogleLogin hook in my page I got the error TypeError: Cannot read properties of undefined (reading 'oauth2'), but when I reload it works and if I when back and forward to signup again it gives me the error again. I can't find oauth2 in the library and can't find a solution for it

**Comment by MomenSherif** [comment]
Can you make sure that GoogleOAuthProvider wraps your application

& If you can provide codesandbox or Repo example with the issue will be great to try it

**Comment by omarwael98** [comment]
I have tried it in a new project but it doesn't give the error ! 
so I guess it's my fault but I don't what did I do wrong. do you have any idea what goes wrong to give that?

**Comment by MomenSherif** [comment]
mmm make sure any hook usage is under <GoogleOAuthProvider /> in the component tree,

or add the provider in Root layout once
