### ISSUE TITLE
There is no response form google's full screen login page(ux_mode:"redirect")

### ISSUE THREAD

**Issue by a5h101** [MomenSherif/react-oauth#298]
```
const handleGoogleLogin = useGoogleLogin({
    flow: 'auth-code',
    ux_mode: 'redirect',
    redirect_uri: 'http://localhost:3000',
    // select_account: true,
    onSuccess: async ({ code }) => {
      try {
        console.log(code);
        const { data } = await axios.post(
          'http://localhost:8000/auth/google',
          null,
          {
            headers: {
              Authorization: `Bearer ${code}`, // Sending the code as a Bearer token
            },
          }
        );
        localStorage.setItem('auth', JSON.stringify(data));
        onClose();
      } catch (error) {
        console.log(error);
        alert('Failed to login');
      }
    },
    onError: (error) => {
      console.log(error);
      onClose();
    },
  });
```

**So here I am trying to make the google login window open in full screen. The full screen window is opening but after I select any of my id to sign in there is no response, no error message no success message, and no console log too.**

Any fix? uri and the redirect url in google client is same. 

-These are some error message I get after the sign in page is opens 
![image](https://github.com/MomenSherif/react-oauth/assets/113436653/3015dc12-15b3-4250-b8dd-c89670d909c2)

**Comment by MomenSherif** [comment]
After successful login from redirect mode, Google redirects back to your URL and attaches authorization code in as query string the URL as I can remember

**Comment by dev-status-200** [comment]
and how to use that code, I mean if we use popup mode the onsucces provides credentials so we can get the email info, but how to extract info from code?
plz help me.

**Comment by a5h101** [comment]
> and how to use that code, I mean if we use popup mode the onsucces provides credentials so we can get the email info, but how to extract info from code? plz help me.

Yes I found a way to get the code but I don't know why that code is not getting verified by google, but when I pass the code which I am getting from pop-up login, it works.

I am using fast api - 
![image](https://github.com/MomenSherif/react-oauth/assets/113436653/a8bf86ff-ed84-40fa-b99c-9c22ab15ce79)

When I use Redirect login in front end and get code - 
![image](https://github.com/MomenSherif/react-oauth/assets/113436653/aff89c67-bf1f-4bb6-9f24-fc89ad6d95ac)

When I use Popup login method in fornt end and get code - 
![image](https://github.com/MomenSherif/react-oauth/assets/113436653/23f84f01-e406-4b93-b984-1c0bad064b1a)

- LoginDialog.jsx
```
 <GoogleButton onClick={handleGoogleLogin} />
  const handleGoogleLogin = useGoogleLogin({
    flow: 'auth-code',
    ux_mode: 'redirect',
    redirect_uri: 'http://localhost:3000/google-callback',
  });
```

- GoogleCallBack.jsx 

```
function GoogleCallback() {
  const location = useLocation();
  const navigate = useNavigate();

  useEffect(() => {
    const searchParams = new URLSearchParams(location.search);
    const code = searchParams.get('code');
    const error = searchParams.get('error');

    const handleGoogleLogin = async (code) => {
      console.log('hi');
      console.log(code);
      try {
        const { data } = await axios.post(Auth('google'), null, {
          headers: {
            Authorization: `Bearer ${code}`, // Sending the code as a Bearer token
          },
        });
        localStorage.setItem('auth', JSON.stringify(data));
        navigate('/');
        // onClose();
      } catch (error) {
        console.log(error);
        alert('Failed to login!');
      }
    };

    if (code) {
      handleGoogleLogin(code);
    } else if (error) {
      console.log('hi2');
      alert('Failed to login!');
      console.log(error);
    }

    // Redirect back to your main app page
    navigate('/');
  }, [location.search, navigate]);

  return <div>Redirecting...</div>;
}

export default GoogleCallback;
```

- App.js
`  <Route path='/google-callback/*' element={<GoogleCallback />} />`

**Comment by Bohan-J** [comment]
@a5h101 Your code helps a lot! Thanks
