### ISSUE TITLE
About using the use_fedcm_for_prompt parameter

### ISSUE THREAD

**Issue by mikdatdogru** [MomenSherif/react-oauth#300]
Google will make a regulation about 3rd party cookies at the end of the year. In order to adapt to this regulation within the scope of beta, it is necessary to use a parameter called "[use_fedcm_for_prompt](https://developers.google.com/identity/gsi/web/reference/js-reference?hl=en#use_fedcm_for_prompt)". 

How can we use this parameter on `<GoogleOAuthProvider>` ?

---
Related links: 
https://developers.googleblog.com/2023/08/announcing-federated-credential-management-beta-for-gis.html
https://github.com/fedidcg/FedCM

**Comment by ninja-rpf** [comment]
Will have to make a few changes to enable fedcm.
https://developers.google.com/identity/gsi/web/guides/fedcm-migration

**Comment by MomenSherif** [comment]
it's added now in latest version 0.12.0
