### ISSUE TITLE
Share google button

### ISSUE THREAD

**Issue by PatrykKuniczak** [MomenSherif/react-oauth#302]
I think, great idea is share to us, google button without action, i mean without popup, and neccessery provider auth process etc.

I want to use it in that way, but i can't and i must recreate it from scratch :)

**Comment by MomenSherif** [comment]
The button in rendered by Google itself in Iframe

You can look for Html, Css google login example on the internet you will find alot

**Comment by PatrykKuniczak** [comment]
I see several, thanks, but if you could do it, u know, as React component, that's could be amazing :)

**Comment by MomenSherif** [comment]
It's out of the scope of the package unfortunately, It's better to give user the control how they like to show their buttons

**Comment by PatrykKuniczak** [comment]
Thanks for quick response :)
