### ISSUE TITLE
When Can we Expect Fed CM Migration

### ISSUE THREAD

**Issue by ninja-rpf** [MomenSherif/react-oauth#303]
<img width="950" alt="Screenshot 2023-09-13 at 6 05 08 PM" src="https://github.com/MomenSherif/react-oauth/assets/106671575/8e7a7f2f-7738-49cd-a7be-18deb71d3346">

Migration Guide:
https://developers.google.com/identity/gsi/web/guides/fedcm-migration

**Comment by ninja-rpf** [comment]
@MomenSherif ?

**Comment by rahmatkurniawantiket** [comment]
I think this is need to implement imddediatly

**Comment by mistryshaan** [comment]
@MomenSherif Please update here once FedCM changes are made in the library. Thanks, in advance.

**Comment by i7N3** [comment]
You can use [google-oauth-gsi](https://github.com/i7N3/google-oauth-gsi).
It has same API, framework agnostic and Supports FedCM.

**Comment by MomenSherif** [comment]
@react-oauth/google@0.12.0 is released with the `use_fedcm_for_prompt` flag if needed

**Comment by ninja-rpf** [comment]
Thanks a Lot @MomenSherif
