### ISSUE TITLE
NextJS 14 | Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

### ISSUE THREAD

**Issue by majdhajyehia** [MomenSherif/react-oauth#313]
Hi, I'm trying to use the package with NextJS 14 with no success. I couldn't find anywhere whether it can work with NextJS 14 or not but I thought I could ask here. Any help would be appreciated.
When I try to run `npm run dev`, the app fails to compile with the error `Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function`
This is my package.json:
`
{
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@react-oauth/google": "^0.11.0",
    "axios": "^1.6.0",
    "next": "14.0.1",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}
`

**Comment by rexwreyes** [comment]
I am trying also.  The issue is simply that @react-oauth is not SSR ready.  if you use createContext you need to also include 'use client' at the top of the doc.  The only option i can think of until they fix this is to download the source, add 'use client' the the relevant files and use that instead of the package.

**Comment by MomenSherif** [comment]
I added `use client` directive to the build output, please try it and mention me if there's an issue

**Comment by alejandro3469** [comment]
> use client

it works!
