### ISSUE TITLE
onSuccess operations when ux_mode is redirect

### ISSUE THREAD

**Issue by dmdum** [MomenSherif/react-oauth#33]
Hello, I'm using redirection instead of popup to login. The the onSuccess prop doesn't seem to be triggered. Am I using this wrong or is this just the expected behavior?

```
const googleLogin = useGoogleLogin({
    flow: 'auth-code',
    select_account: true,
    ux_mode: "redirect",
    redirect_uri: "http://localhost:3000/preview/",
    onSuccess: async ({ access_token }) => {
      {...}
    },
    onError: () => {...},
});
```
Thanks!

**Comment by sollych** [comment]
Please have a look at this:

https://github.com/anthonyjgrove/react-google-login/issues/165

**Comment by MomenSherif** [comment]
Hello @dmdum, `onSuccess` will not be triggered in redirect mode.
instead, Google will redirect you back to the given URL with query param `code`
like that `http://localhost:3000/preview/?code=xxxxxxxxxxxxxxxxxx&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&prompt=consent`

You can get code from query parameters in the URL
