### ISSUE TITLE
useGoogleLogin works in development but fails with production build

### ISSUE THREAD

**Issue by sollych** [MomenSherif/react-oauth#34]
I am using the implicit flow to get the tokenResponse from google and then send the token to my backend. Everything works perfectly fine in local development but when I build the react for production, the login does not work at all. There are no errors received at all.

```javascript
const googleLogin = useGoogleLogin({
    flow: "implicit",
    onSuccess: (tokenResponse) => {
      console.log(tokenResponse);
      // Send the google token to the backend to get access and refresh tokens
      dispatch(
        googleLoginRequest({
          access_token: tokenResponse.access_token,
        })
      );
    },
    onError: (errorResponse) => console.log(errorResponse),
  });
```

I am not sure if there is something that is not being included in the build or not because I have cleared cache, changed browsers and it all seems to work in development and not in production with the react build.

**Comment by MomenSherif** [comment]
Make sure you added your production URL to Google console settings.

and maybe it's related to CSP `content security policy` to be enabled for google or something like that in this issue https://github.com/MomenSherif/react-oauth/issues/17

**Comment by sollych** [comment]
Thanks. However I had to use the ux_mode: "redirect" and then grab the code from the URL params. Somehow auth code flow with popup is not working with the build even after looking into CSP.

**Comment by TranTruongMinhThang** [comment]
@sollych Could you guide me the way to take the refresh token for use with Google Calendar API - do I change flow to auth-code?
thank you so much

**Comment by TranTruongMinhThang** [comment]
[](https://github.com/MomenSherif/react-oauth/issues/6#issuecomment-1127381653)
I found this, thank you so much
