### ISSUE TITLE
Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by punter82** [MomenSherif/react-oauth#343]
Please ignore this. It was a configuration error. It has been resolved.

**Comment by punter82** [comment]
Anyone with an insight on the above issue ? Do we need to pass the redirect URI to the GoogleOauthProvider ?

**Comment by ammarraj** [comment]
I think posting what was the issue and how was it fixed might help others. For me I was missing this part of the configuration (from Readme):

> Key Point: Add both http://localhost and http://localhost:<port_number> to the Authorized JavaScript origins box for local tests or development.
