### ISSUE TITLE
Refresh token on success

### ISSUE THREAD

**Issue by Vette1123** [MomenSherif/react-oauth#357]
I'm using your library, good job making this its so useful!, 

the response i'm getting when i login with google (doesn't have a refresh token)

why there is no refresh_token returned?, my business requires a refresh token, but i can't get it using your library, can you kindly support?

**Comment by MomenSherif** [comment]
https://github.com/MomenSherif/react-oauth/issues/6#issuecomment-1127381653

authorization code flow and exchange it with tokens

**Comment by Vette1123** [comment]
tmam shukrn lek gdn <3 
    On Wednesday, July 10, 2024 at 12:27:11 PM GMT+3, MomenSherif ***@***.***> wrote:  
 
 


#6 (comment)

authorization code flow and exchange it with tokens
