### ISSUE TITLE
Facing issues after install: Invalid hook call. Cannot read property of null (reading 'useState'). 

### ISSUE THREAD

**Issue by Saraphite** [MomenSherif/react-oauth#358]
Hey there!

I've recently added this package to my project and have followed the docs (twice) and I still end up with the same issue.

These are the errors:
![image](https://github.com/user-attachments/assets/d4ab79c8-ae4e-48a5-bee8-4cec9f819804)

This is all I've added. (ClientId is redacted)
![image](https://github.com/user-attachments/assets/e4aad0bb-76de-47a6-8213-d900c8cdf1eb)

If I remove the above then my application works again.

I'm using React 18.3.1 and Vite.js 5.2.0.

Please forgive me if I'm missing something obvious - I'm fairly new to front end development.

**Comment by Saraphite** [comment]
I managed to resolve this by doing one of the following things, though I'm not sure which one:

1. Restarted my computer
2. Deleted node_modules and then `npm install`
3. Tried building a duplicate project with the same dependencies to see when it would break (spoilers, it didn't).
4. Watched Oppenheimer
5. Had a good nights sleep.

If you're facing a similar issue, I'd recommend trying the above.

**Comment by cravall** [comment]
I'm running into this error... I've already watch Oppenheimer, not sure I want to watch it again.

**Comment by mKepka16** [comment]
I'm getting the same problem, both with react 18 and 19 from vite template (no SWC).
