### ISSUE TITLE
Provide credential (jwt) in response for custom button

### ISSUE THREAD

**Issue by mp3846** [MomenSherif/react-oauth#37]
import { useGoogleLogin } from '@react-oauth/google';

const login = useGoogleLogin({
  onSuccess: credential=> console.log(credential),
  flow: 'jwt',
});

<MyCustomButton onClick={() => login()}>
  Sign in with Google 🚀{' '}
</MyCustomButton>;

**Comment by MomenSherif** [comment]
flow `jwt` is not valid value

If you need to have jwt in custom button please check flow `auth-code`

You can find examples provided here 

https://react-oauth.vercel.app

**Comment by mp3846** [comment]
Thank you for answering quickly
I tried auth-code but it does not return a jwt like one-tap
I need jwt credential to verify it in backend using verifyIdToken method from google-auth-library which expects a jwt for its idToken property

**Comment by MomenSherif** [comment]
It will require little changes in the backend to get JWT In auth-code flow

Backend example is provided in this comment
https://github.com/MomenSherif/react-oauth/issues/12#issuecomment-1131408898

Your backend should exchange `code` token with access, id and refresh tokens
