### ISSUE TITLE
Getting Error: Google OAuth components must be used within GoogleOAuthProvider

### ISSUE THREAD

**Issue by TangoPJ** [MomenSherif/react-oauth#38]
Hello. I'm trying to get auth code from google and send it to server side to get tokens. But when I wrapped my custom button to the GoogleOAuthProvider component I got the error like on the screenshot:

![image](https://user-images.githubusercontent.com/64611024/173199771-296c5249-560c-49d7-a8c9-7a0a3d68b50d.png)

I'm doing everything like in documentation, but don't understand where I could make a mistake...

this is my component's code:

```
/* eslint-disable react/button-has-type */
import { GoogleOAuthProvider, useGoogleLogin } from '@react-oauth/google';
import { Button, message } from 'antd';
import { setApiHeader } from 'api/axios';
import { userAuth } from 'api/requests/userAuth';
import React from 'react';
import { useHistory } from 'react-router-dom';
import { localStorageKeys } from 'resources/localStorageKeys';
import { saveState } from 'utils/localStorage';

const GoogleAuth = () => {
  const clientId = process.env.REACT_APP_GOOGLE_CLIENT_ID || '';
  const history = useHistory();

  const login = useGoogleLogin({
    onSuccess: async (res: any) => {
      try {
        const { data } = await userAuth(res);
        saveState(data, localStorageKeys.radiatorUser);
        setApiHeader('Authorization', `Bearer ${data?.token}`);
        history.push('/');
        if (data) void message.success('Success');
      } catch (error) {
        void message.error(error.message);
      }
    },
    flow: 'auth-code',
  });

  return (
    <GoogleOAuthProvider clientId={clientId}>
      <Button onClick={() => login()}>Sign in with Google 🚀 </Button>
    </GoogleOAuthProvider>
  );
};

export default GoogleAuth;


```

**Comment by MomenSherif** [comment]
Hello @TangoPJ 

`useGoogleLogin` need to be inside `GoogleOAuthProvider` you can lift the provider up one level and it will work

**Comment by TangoPJ** [comment]
@MomenSherif  Please, can you send a code example, how it should look like?

**Comment by MomenSherif** [comment]
I'm using mobile right now, so I can't write some code

But you can do it inside your react entry point like this

https://github.com/MomenSherif/react-oauth/blob/master/apps/playground/src/index.tsx

Or wrap your GoogleAuth component with the provider directly both will work

**Comment by TangoPJ** [comment]
@MomenSherif Thank you very much, I'll try the second way (wrap my GoogleAuth component with the provider directly) ;)

**Comment by TangoPJ** [comment]
@MomenSherif  It worked for me, thank you so much! =) I can close the question

**Comment by mplacona** [comment]
Hey @TangoPJ sorry to barge in on a closed issue, but wondering if you could show me an example of how to wrap your GoogleAuth component with the provider directly. Thanks
