### ISSUE TITLE
How to recognize start of authentication flow?

### ISSUE THREAD

**Issue by niksauer** [MomenSherif/react-oauth#40]
While migrating from [react-google-login](https://github.com/anthonyjgrove/react-google-login) I noticed that there is no way to get notified when the authentication flow actually starts (`onRequest`), i.e. when the user has clicked the _Sign in with Google_ button. Such a callback, however, is needed to instruct other components to reset their state, especially when performing multiple login attempts upon failure and mixing this with a password-based sign in or other social providers.

Previously, this was possible by overloading the button's onClick handler. This approach does not work anymore since the button will be injected as an iframe.

How can I now recognize when a user has clicked _Sign in with Google_?

**Comment by MomenSherif** [comment]
It seems stupid solution, but maybe work for click but will not work for using keyboard

You can wrap google button with with div and use onClick on it, maybe on click event will fire i am not sure


Or if you wanna to control onClick you can go with the custom hook solution

**Comment by niksauer** [comment]
This is now officially supported using the [new `click_listener` option](https://github.com/google/google-api-javascript-client/issues/819#issuecomment-1349908594) in `GsiButtonConfiguration`. Please see my PR #150.
