### ISSUE TITLE
How to silent login?

### ISSUE THREAD

**Issue by andra961** [MomenSherif/react-oauth#41]
Hi @MomenSherif, thank you for your library. In other similar libraries there was a silent login feature, where the user would silently login again in the app when launching it. How does it work here?do i need to login each time i open the app from the beginning?how do i check if a user is still logged in when i launch it?

**Comment by MomenSherif** [comment]
Hello @andra961,

Google no longer manages user login session, It's our responsibility now.
You can persist user where you want, cookies, localstorage ... etc, and you can check if token expired or not to make sure user is logged in
