### ISSUE TITLE
Why may happen no console logs after I selected account in Google auth popup?

### ISSUE THREAD

**Issue by lofti198** [MomenSherif/react-oauth#43]
Hi! Using this code:

```
import { GoogleLogin } from '@react-oauth/google';

<GoogleLogin
  onSuccess={credentialResponse => {
    console.log(credentialResponse);
  }}
  onError={() => {
    console.log('Login Failed');
  }}
/>;
```
Also wrapped app component with GoogleOAuthProvider . However when I click button and then select account in Google auth popup, I see nor success, neither error logs. What could be the reason?

**Comment by MomenSherif** [comment]
Hi @lofti198, 

Maybe it's related to CORS issue, maybe this issue will help https://github.com/MomenSherif/react-oauth/issues/17

**Comment by lofti198** [comment]
> Hi @lofti198,
> 
> Maybe it's related to CORS issue, maybe this issue will help #17

Thank you for fast reply! In this case #17 , as far as I understood the issue was solved by turning crossOriginOpenerPolicy to false **on backend**, however I'm still not connected backend to my project. Or maybe I'm misunderstanding on what side I should change cors setting? I would appreciate if you clarify this for me.
