### ISSUE TITLE
Can I somehow customize the expiration period?

### ISSUE THREAD

**Issue by lofti198** [MomenSherif/react-oauth#49]
Can I somehow customize the token expiration period? As far as I understand it is 1 hour by default.

**Comment by MomenSherif** [comment]
Unfortunately it's not, google doesn't provide a way to control it.

**Comment by lofti198** [comment]
Thank you for reply!  Maybe it provides refresh token so I can keep user authorized without involving his efforts?

**Comment by MomenSherif** [comment]
Yes, you can get refresh token through authorization code flow from custom hook

You can follow this comment for backend example with express

https://github.com/MomenSherif/react-oauth/issues/12#issuecomment-1131408898
