### ISSUE TITLE
Accessing current Logged In user data!!!

### ISSUE THREAD

**Issue by eshan1925** [MomenSherif/react-oauth#51]
How can we access the details like email-id, profile picture link, Name and stuffs like that for the current logged in user.

**Comment by MomenSherif** [comment]
If you are using `GoogleLogin` you can decode credential property onSuccess response with jwt-decode

And you can follow the demo will tell you how to get user info based on using the component or the hook

https://react-oauth.vercel.app

**Comment by eshan1925** [comment]
Hey, @MomenSherif I still am unable to get how to do that...
Can you please elaborate, actually I am new to all this and I want to learn.

**Comment by MomenSherif** [comment]
Sure, I will send you a full detailed example tomorrow

**Comment by MomenSherif** [comment]
First of all, you need to wrap your application with `GoogleOAuthProvider` to provide google's client id to `GoogleButton`

```jsx
<GoogleOAuthProvider clientId="<YOUR_CLIENT_ID>">
    <App />
</GoogleOAuthProvider>
```

inside your app or login page, you can use `GoogleLogin` component to render google's personalized button, and on successful login, it will return you an object with credential property on it, which is a JWT containing user's info

I used here `jwt-decode` to be able to decode JWT for stored info in it

```jsx
import { GoogleLogin } from '@react-oauth/google';
import jwtDecode from "jwt-decode";

function LoginPage() {
  return (
      <GoogleLogin onSuccess={({ credential }) => {
          const userInfo = jwtDecode(credential);
          console.log(userInfo)
      }}/>
  );
}
```

**Comment by eshan1925** [comment]
Thank you so much @MomenSherif . Really everything was explained nicely....

Also, it would be of great help if you could recommend the same type of service for Facebook login

**Comment by MomenSherif** [comment]
There are some packages that do OAuth for face book like react-facebook-login

I didn't use it before, But maybe I will make my own one to be @react-oauth/facebook to have similar API to google in one or two weeks
