### ISSUE TITLE
Popup Screen is blank show in production environment 

### ISSUE THREAD

**Issue by websiteaap** [MomenSherif/react-oauth#52]
Hello MomenSherif 
I am using react-oauth package so it is working in localhost but it does not work in production environment.
Can suggest how to solve these issue.

It is screen shot of our live production environment issues
https://user-images.githubusercontent.com/53229705/177474714-71f29ea5-2597-4d0a-91e7-634f43979009.png

**Comment by MomenSherif** [comment]
Hello,

Please make sure to add your production URL to google developer console in `Authorised JavaScript origins` section

**Comment by sanjay-subskribe** [comment]
I faced same problem. I was able to solve by changing CORS policy as below:

Cross-Origin-Opener-Policy: same-origin-allow-popups

Savior reference -
https://github.com/google/google-api-javascript-client/issues/796#issuecomment-1118136612
