### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'requestAccessToken')

### ISSUE THREAD

**Issue by jaykmark** [MomenSherif/react-oauth#54]
We're using the `useGoogleLogin()` hook and the library is working great overall but we're seeing a low volume of type error bugs: `TypeError: Cannot read properties of undefined (reading 'requestAccessToken')`. ~80% on Mobile Chrome Web. It looks like `.requestAccessToken` is part of [this ref](https://github.com/MomenSherif/react-oauth/blob/8ed49b8ef6cd6f59fd11c233fe8157a381413076/packages/%40react-oauth/google/src/hooks/useGoogleLogin.ts#L105). Any ideas on a potential fix or something we can do in our client-side code? Thanks!

**Comment by MomenSherif** [comment]
I think it will only throw an error, if google gsi script was not be able to download

You can lister for success or failure of loading script from props on GoogleOAuthProvider
