### ISSUE TITLE
Locale property is not working?

### ISSUE THREAD

**Issue by Bodrie** [MomenSherif/react-oauth#56]
To be honest I'm not sure if I am doing something wrong but it seems that the `locale` property of the the `GoogleLogin` component isn't working, in your and in the google documentation is stated that: `locale: string`, e.g. "zh_CN", but even the example isn't working.

Is this the case or I miss understhood something?

**Comment by Bodrie** [comment]
Sorry but that is pretty inappropriate, to close and mark the issue as invalid w/o any explanation or further discution...

**Comment by Bodrie** [comment]
![Screenshot 15-07-2022](https://user-images.githubusercontent.com/80153626/179234779-b09d057e-acc0-48ce-8dd6-7de855fad187.png)

**The locale is set...**

![Screenshot 15-07-2022_1](https://user-images.githubusercontent.com/80153626/179234800-e64e11a4-6cd6-4da1-8f5c-630cf92f6bbe.png)

**The button stays in the browser def lang...**

**Comment by MicheleFatticcioni** [comment]
Still not working


`
<GoogleLogin
				shape={"circle"}
				text={"signin_with"}
				context={'signin'}
				locale={locale}
				/*@ts-ignore*/
				onSuccess={successHandler}
				onFailure={handleFailure}
				
			/>
`

**Comment by MicheleFatticcioni** [comment]
Why this issue is marked as invalid? I have the same problem with the locale props

**Comment by Crsk** [comment]
> https://developers.google.com/identity/gsi/web/reference/js-reference#locale
> 
> > The pre-set locale of the button text. If it's not set, the browser's default locale or the Google session user’s preference is used. Therefore, different users might see different versions of localized buttons, and possibly with different sizes.
> 
> Maybe the user account has a strong preference that google respects.

![image](https://github.com/MomenSherif/react-oauth/assets/6186848/d99542d1-313b-4cc0-9837-dcb6a0f0df2f)

From the Google side, the user account has not a strong preference, so the `locale` property should also have priority over Google account and browser.

BTW, the `locale` is not working for me either, same as @Bodrie I did set the property and the button stays in another lang which in my case is Spanish. Seems like this is not working if your default Google account or browser is set to other than English

**Comment by buraketmen** [comment]
any update?

**Comment by Whitelistedd** [comment]
doesnt work for me too

**Comment by andriiwp3** [comment]
Hey guys! I have ran into this issue as well
The reason why this doesn't work according to Google's documentation is that the library doesn't pass the hl directive

> Add the hl parameter and language code to the src directive when loading the library, for example: gsi/client?hl=\<iso-639-code\>
> 
> If it's not set, the browser's default locale or the Google session user's preference is used

I have found a workaround to get around it for now

This works perfectly for me, so feel free to use it. In the meantime, I'll try to open a PR to this repo to fix the issue globally

```jsx
  const onScriptLoaded = () => {
    document.body.removeChild(document.querySelector('[src="https://accounts.google.com/gsi/client"]'));
    const scriptTag = document.createElement('script');
    scriptTag.src = `https://accounts.google.com/gsi/client?hl=${locale}`;
    scriptTag.onload = () => {
      setIsReady(true);
    };
    document.body.appendChild(scriptTag);
  };

  return (
    <div ref={ref}>
      <GoogleOAuthProvider
        clientId={googleSignInToken}
        onScriptLoadSuccess={onScriptLoaded}
      >
        {isReady && <GoogleLogin {...props} />}
      </GoogleOAuthProvider>
    </div>
  );
```

**Comment by andriiwp3** [comment]
Here we go
- https://github.com/MomenSherif/react-oauth/pull/370
