### ISSUE TITLE
Why docs recommend against using `state` value in `useGoogleLogin`

### ISSUE THREAD

**Issue by tyler-hitzeman** [MomenSherif/react-oauth#58]
The "useGoogleLogin (Extra implicit flow props)" section of the README says the `state` value is "Not recommended". Why is that? 

Google's OpenID / Oauth2 docs recommend using state to prevent CSRF attacks:

> You must protect the security of your users by preventing request forgery attacks. The first step is creating a unique session token that holds state between your app and the user's client. You later match this unique session token with the authentication response returned by the Google OAuth Login service to verify that the user is making the request and not a malicious attacker. ([source](https://developers.google.com/identity/protocols/oauth2/openid-connect#createxsrftoken))

 I'm just curious if there's something I'm missing.

**Comment by MomenSherif** [comment]
Google recommends to use it if you are interacting with a server, ( using authorization code flow )

> Recommended for redirect UX. Specifies any string value that your application uses to maintain state between your authorization request and the authorization server's response

Actually, all docs text here from google's reference on each login flow

**Comment by tyler-hitzeman** [comment]
I'm a little confused. The `useGoogleLogin` hook can be used for  authorization code flow. And google recommends using state for the authorization code flow. So shouldn't the docs recommend using `state` with `useGoogleLogin` instead of discouraging it (by saying it's "Not recommended")? 

I know I'm being picky, but that "Not recommended" line in the docs made me confused for a bit, and I think others reading it will feel the same. So clarifying this in the docs would make it easier to adopt. I can make a PR that changes it from "Not recommended" to "Recommended" if you'd like

**Comment by MomenSherif** [comment]
useGoogleLogin can be used for authorization code flow which required backend and can be used for implicit flow which doesn't required backend

In the docs you will find each one state is defined in the README
