### ISSUE TITLE
Is there a way to specify scopes in Google Login component?

### ISSUE THREAD

**Issue by gpersonnat** [MomenSherif/react-oauth#59]
<img width="639" alt="Screen Shot 2022-07-20 at 11 49 16 AM" src="https://user-images.githubusercontent.com/89941578/180026713-60475f5b-1c1e-476c-8ec0-8c75aa535284.png">

Is there a way to specify scopes other (than the profile information) by passing in props to the GoogleLogin component, so I can allow users to authorize Google Drive or Google Google docs?

**Comment by MomenSherif** [comment]
Yes, but you need to use `useGoogleLogin` for authorization and defining scopes

**Comment by gpersonnat** [comment]
How can I add use the GoogleLoginButton instead of a custom button (without importing a button from another library)?

**Comment by MomenSherif** [comment]
You can't with personalized button to define scopes, Google doesn't provide a way

You can copy/paste snippets for custom google css button on the internet

**Comment by gpersonnat** [comment]
`import GoogleButton from 'react-google-button'
import { useGoogleLogin, GoogleOAuthProvider } from '@react-oauth/google';

export default function GoogleButtonUse() {
    
const login = useGoogleLogin({
        onSuccess: tokenResponse => console.log(tokenResponse),
      });
      

      return (
      <GoogleOAuthProvider clientId="977649915328-voaootijhsdd0onsfpobeeoj5nq6g8i3.apps.googleusercontent.com">
            <GoogleButton 
            onClick={login}

        />

       </GoogleOAuthProvider>
        
    );

}`
Why can't I define the login function outside the GoogleAuthProvider? Defining it inside it doesn't work either?

**Comment by gpersonnat** [comment]
Bumping my above reply.

**Comment by MomenSherif** [comment]
Your code snippets doesn't use the hook inside the provider it's called outside.


Make the provider one up level

**Comment by gpersonnat** [comment]
Wrap it around the return statement or GoogleButton Use Component? Could you provide an example if you have time? I appreciate your quick response.

**Comment by MomenSherif** [comment]
I can't for now sorry, i'm using mobile to reply

You can add the wrap google provider above <App /> it will work like redux provider or any other provider

And you can check in repo files playground folder have example used in it

**Comment by gpersonnat** [comment]
Where in the playground folder? I don't see an example of GoogleOAuthProvider being used?

**Comment by MomenSherif** [comment]
https://github.com/MomenSherif/react-oauth/blob/master/apps/playground/src/index.tsx
