### ISSUE TITLE
Where is the backend code to exchange code for tokens? 

### ISSUE THREAD

**Issue by gpersonnat** [MomenSherif/react-oauth#60]
<img width="876" alt="Screen Shot 2022-07-20 at 4 53 50 PM" src="https://user-images.githubusercontent.com/89941578/180080181-689ce017-f0c4-40d3-bcee-47d9be40ff09.png">

What repository is this code in?

**Comment by MomenSherif** [comment]
Click on `check backend` it's a link to a comment that has express example

And you I had a playground just for trial if you wanna check also

https://github.com/MomenSherif/google-oauth2-playground-server

But the comment example should be more than enough
