### ISSUE TITLE
Button for Authorization code flow

### ISSUE THREAD

**Issue by lthamm** [MomenSherif/react-oauth#63]
Hi, first of all thank you very much for this library! 
What is the idea behind allowing the Authorization code flow only with a custom button? Google allows the login only with a button that conforms to their guidelines, so everyone using the auth code flow will need to implement the same button.
Am I missing the point behind this or is there actually a function that would allow using a library button?

**Comment by MomenSherif** [comment]
Hello @lthamm 

Google gives the new personalized button for only seamless sign-in flows, without any authorization can be done
https://developers.google.com/identity/gsi/web

and If it's needed to get authorization access token to talk to google APIs we can use google's authorization flow which comes without any style given from google, not from @react-oauth/google implementation.
It's just here as a small layer for React to have a nicer API.

**Comment by lthamm** [comment]
Thanks for your response! I am not sure however, if I understand it correctly.
In https://github.com/MomenSherif/react-oauth/blob/176fe71b8f721b0dd42197d02041caa23ec42291/packages/%40react-oauth/google/src/GoogleLogin.tsx#L63, you render the google button. Can't the same button be used for the authorization code flow? 
If I use a "custom" button, I will need to access the window.google object again (and everyone using this library will need to do so, building the same thing again). After all a truly custom button is not allowed, as google only allows its own button to be used.

**Comment by MomenSherif** [comment]
Truly custom buttons are allowed in the custom hook, google doesn't have any constrains on the button

https://react-oauth.vercel.app
You can check authorization here it uses chakra button


For the custom button, I don't render it by myself google injects it in iframe when I request from them to use seamless sign flow


And you can't control the onClick inside iframe so we are nit able to use this button with authorization flows
You can get snippets from the internet for buttons similar to google

**Comment by lthamm** [comment]
From their own documentation Google does have constraints on how buttons can look: https://developers.google.com/identity/branding-guidelines
And from my experience, an app won't get approved if you do not follow those guidelines. 

Why would you need to control the onClick? You can just return the Google button and handle the authorization code in the onSuccess (just like it has been done with the old wrapper for the old library https://github.com/anthonyjgrove/react-google-login). Maybe I am just missing your point or something new about the implementation?

**Comment by MomenSherif** [comment]
Google is not following the same rules and API exposed used on old library

I just did a small wrapper around the new implementation for react for easier usage.

You can't return that button in a variable like this, we had no control google runs their code and inject iframe in which contains the button
You can clone the repo and run the dev mode and try to do your proposal to know what what I mean.

And google is ok with any design you put in the button and if you wanna follow their recommendation for style
Use CSS to create a button that looks like google

**Comment by lthamm** [comment]
I think there is some misunderstanding. 
But I looked into the code and the google documentation more and I now understand the problem. `renderButton` depends on `intialize` and `intialize` is for returning the credential response containing the identity jwt only. It is not for oauth. I wonder why however.

> And google is ok with any design you put in the button and if you wanna follow their recommendation for style
This previously has not been true. I got appeals for apps when buttons only minimally differed from the branding guidelines. I don't know how it changed with the new library, but the (branding guidelines)[https://developers.google.com/identity/branding-guidelines] do not have a deprecation notice. 
I assume that google would like anyone to use the `renderButton` for authentication and the oauth methods for authorization, so in that case there would never be the need for a custom login (authentication) button, only for a authorization button.

See:
https://developers.googleblog.com/2022/02/announcing-authorization-support-for.html
and especially:
https://developers.googleblog.com/2022/03/gis-jsweb-authz-migration.html

> Your web application may use both authorization (to call Google APIs), and authentication (to manage user sign-in to your app). If this is the case, you’ll need to follow both migration guides to ensure separation of user authorization and authentication flows in your web application.

**Comment by MomenSherif** [comment]
Try to follow the migration for authorization button or authorization flow from the beginning you will find that it will not render with the new button

It's easy to implement from their docs

**Comment by lthamm** [comment]
> you will find that it will not render with the new button
This is what I said in my latest comment.

**Comment by MomenSherif** [comment]
That's good ✌🏻 sorry my bad.

**Comment by lthamm** [comment]
No worries! My concern was: I doubt that Google will approve custom login buttons with the code flow. 
This is especially critical for migrating in production applications.

**Comment by MomenSherif** [comment]
Yes it will accept the application

**Comment by lthamm** [comment]
How do you know? Is it documented somewhere?

**Comment by MomenSherif** [comment]
Not documented, But if they don't provide the button for authorization how should it be done ....

And found some people are using it on production with custom button

**Comment by lthamm** [comment]
> how should it be done ....

Theoretically at least two options:
1. In a two step manner: Authentication with their provided button ("Login") followed by authorization with a button you provide yourself ("Grant rights")
2. Creating a button according to their guidelines (as before)

If its not documented, it would be pretty risky to migrate an in production app that way, because if it receives an appeal, it will break the application.

**Comment by MomenSherif** [comment]
You can use authorization flow only for authentication and authorization
You don't need to have 2 steps If you don't want


Lastly I gave you all options I know, you can pick what fits you

**Comment by lthamm** [comment]
> You can use authorization flow only for authentication and authorization

I know, but it seems like Google does not want you to do that (https://developers.googleblog.com/2022/03/gis-jsweb-authz-migration.html). It is a bit vague however. I think this is just not very well documented. 

Again: Thank you. In the end I guess I'll just need to try to get a demo app verified and then migrate the production apps.

**Comment by MomenSherif** [comment]
Cool ✌🏻
