### ISSUE TITLE
Error: invalid_grant

### ISSUE THREAD

**Issue by AlDiAlisel** [MomenSherif/react-oauth#64]
Hi, i try to improve google auth with your component but from back-end when pass credential i have this error UnhandledPromiseRejectionWarning: Error: invalid_grant but whit the same credential in vue js  all worck well with same credential and same back-end

fom front-end i have this obj after click the button login : {
 
clientId:"clientId"
credential:"credential"
select_by: "btn"

}

export const verifyCode = async  (req,resp)=> {
    const client = new OAuth2Client(
    {
        clientId: 'clientid',
        clientSecret: 'secret',
        redirectUri: 'http://localhost'
    }
)
    const{code}= req.body;
    let { tokens } = await client.getToken(code)
    client.setCredentials({ access_token: tokens.access_token })
    const userinfo = await client.request({
      url: 'https://www.googleapis.com/oauth2/v3/userinfo'
    })
    resp.status(200).json({messaggio:userinfo.data})
  }

**Comment by MomenSherif** [comment]
https://github.com/MomenSherif/react-oauth/issues/12#issuecomment-1131408898

You can follow this express example, replace redirectUri with postmessage

and here you can find a random playground I was using https://github.com/MomenSherif/google-oauth2-playground-server

**Comment by nickyoung87** [comment]
I got this same issue and when I tried to use the express example I get an error also:

```Error: invalid_request
    at Gaxios._request (C:\Users\Nick Young\Desktop\node-google\node_modules\gaxios\build\src\gaxios.js:130:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async OAuth2Client.getTokenAsync (C:\Users\Nick Young\Desktop\node-google\node_modules\google-auth-library\build\src\auth\
oauth2client.js:124:21)
```

**Comment by primenik** [comment]
Uncaught GaxiosError Error: unauthorized_client
I cross checked with frontend and backend, both using same client


`import { OAuth2Client } from 'google-auth-library'

const oAuth2Client = new OAuth2Client(
  process.env.GOOGLE_CLIENT_ID,
  process.env.GOOGLE_CLIENT_SECRET,
  'postmessage' // Redirect URI
);


const getUserInfo = async (code) => {
  try {
    // Exchange code for tokens
    const { tokens } = await oAuth2Client.getToken(code);
    oAuth2Client.setCredentials(tokens);

    // Fetch user info using the access token
    const userInfo = await oAuth2Client.request({
      url: 'https://www.googleapis.com/oauth2/v1/userinfo',
    });

    return userInfo.data; // Return user info
  } catch (error) {
    console.error('Error fetching user info:', error.message);
    throw new Error('Failed to retrieve user information');
  }
};`
