### ISSUE TITLE
Token Error

### ISSUE THREAD

**Issue by SanjayBikhchandani** [MomenSherif/react-oauth#65]
![image](https://user-images.githubusercontent.com/63910275/181263882-35ea8d2d-4339-4659-a9e3-7dfb22dc3409.png)

@MomenSherif I'm getting this error while using **useGoogleLogin()** hook, but still, I'm getting an access token.
Can you pls help me how to fix that error?

FYI, I am using custom button

**Comment by MomenSherif** [comment]
Are you using gapi to talk to google services?

Regardless using the package to login

**Comment by SanjayBikhchandani** [comment]
No, @MomenSherif 
I've just added one custom button, **useGoogleLogin()** hook & **GoogleOAuthProvider** as wrapper to the App.

I'm able to log in successfully but still, I'm getting this warning

**Comment by MomenSherif** [comment]
Really don't know, 

didn't face this warning before
