### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by GodsonAddy** [MomenSherif/react-oauth#66]
Guys please I need help. I'm having difficulty making my code work accurately with the react-oauth/google in my React app. I can't figure out what I'm doing wrong or missing

index.js
` <GoogleOAuthProvider clientId={process.env.REACT_APP_GOOGLE_CLIENT_ID}>
          <App />
        </GoogleOAuthProvider>`

node.js
`const { OAuth2Client } = require("google-auth-library");

const client = new OAuth2Client({
  clientId: `${process.env.REACT_APP_GOOGLE_CLIENT_ID}`,
  clientSecret: `${process.env.GOOGLE_SECRETS}`,
});

router.post("http:localhost:5000/api/auth/users/googlelogin", async (req, res) => {
  const { credential } = req.body;
  client
    .verifyIdToken({
      credential: credential,
      aud: `${process.env.REACT_APP_GOOGLE_CLIENT_ID}`,
    })
    .then((response) => {
      const { email_verified, email, name, given_name, family_name } =
        response.payload;

      if (email_verified) {
        Users.findOne({ email }).exec((err, user) => {
          if (err) {
            return res.status(400).json({
              msg: "There's an error ",
            });
          } else {
            if (user) {
              const jwtToken = jwt.sign(
                { id: user._id },
                process.env.JWT_SECRET,
                {
                  expiresIn: "12h",
                }
              )

              res
                .header("x-auth-token", jwtToken)
                .status(200)
                .send({
                  success: true,
                  jwtToken,
                  user: {
                    id: user._id,
                    name: user.name,
                    email: user.email,
                  },
                });
            } else {
              let password = email + process.env.JWT_SECRET;
              let newUser = new Users({
                email,
                password,
                first_name: given_name,
                last_name: family_name,
                name,
              });
              const addedUser = newUser.save();
              if (!addedUser)
                return res.status(400).json({ msg: "Can't add new blogger" });

              const jwtToken = jwt.sign(
                { id: addedUser._id },
                process.env.JWT_SECRET,
                {
                  expiresIn: "12h",
                }
              );

              res
                .header("x-auth-token", jwtToken)
                .status(200)
                .json({
                  jwtToken,
                  user: {
                    id: addedUser._id,
                    name: addedUser.name,
                    email: addedUser.email,
                  },
                });
            }
          }
        });
      }
    });
});
`

Redux action
`const googleURL = "http://localhost:5000/api/auth/users/googlelogin";

const googlelogin = async (userData) => {
  const res = await axios.post(googleURL, userData);

  if (res.data) {
    localStorage.setItem("token", JSON.stringify(res.data));
  }

  return res.data;
};

export const authGooglelogin = createAsyncThunk(
  "auth/googlelogin",
  async (user, thunkAPI) => {
    try {
      return await googlelogin(user);
    } catch (error) {
      const message =
        (error.response &&
          error.response.data &&
          error.response.data.message &&
          error.response.data.error) ||
        error.message ||
        error.toString();

      return thunkAPI.rejectWithValue(message);
    }
  }
);
`

signup.js
`
import { GoogleLogin } from "@react-oauth/google";
import jwtDecode from "jwt-decode";

function SignUp() {

 const googleLogin = async (response) => {
    console.log(response.credential);
    const user = jwtDecode(response.credential);
    console.log(user);
    const resultAction = await dispatch(authGooglelogin(response.credential));

    console.log(resultAction);

    if (authGooglelogin.fulfilled.match(resultAction)) {
      const user = resultAction.payload;
      console.log("user", user);
      toast.success(`Welcome back ${user.name}`);
    } else {
      console.log(authMessage);
      if (resultAction.payload) {
        //toast.error(`Login failed: ${resultAction.payload}`);
        console.log("error success", resultAction.payload);
      } else {
        toast.error(`Login failed`);
        //console.log("error error", `${resultAction.error.message}`);
      }
    }
  };

  return (

`<GoogleLogin
            onSuccess={googleLogin}
            onError={googleLogin}
            size="large"
            text="signup_with"
            width="700"
            shape="square"
            logo_alignment="center"
          />`
)
}`

I'm using
- React
- Nodejs
- Mongoose
- MongoDB
- Redux Toolkit
- jsonwebtoken
- google-auth-library
- react-oauth/google

**Comment by MomenSherif** [comment]
Try to follow these backend example

Make sure it's working after that integrate it with your DB

https://github.com/MomenSherif/react-oauth/issues/64#issuecomment-1195665620
