### ISSUE TITLE
Why are the response coming from googleLogin and usegoogleLogin responses are different?

### ISSUE THREAD

**Issue by adasarpan404** [MomenSherif/react-oauth#67]

**Comment by adasarpan404** [comment]
I am using this dependencies in my project.

**Comment by MomenSherif** [comment]
They do different things so google respond with different payload

For personalized button it's used for seamless sign in without ability for authorization so it returns user info in JWT

Custom button uses google authorization flow which allow us to authenticate and authorize to call google APIs so it returns useful payload to authorize

**Comment by adasarpan404** [comment]
which google APIs?
Can you please give me some good documentations?

**Comment by MomenSherif** [comment]
https://developers.google.com/identity/gsi/web

seamless sign in response https://developers.google.com/identity/gsi/web/reference/js-reference#CredentialResponse

Authorization flows response https://developers.google.com/identity/oauth2/web/reference/js-reference

All from google docs if you want to know why they are different.

Authorization to google APIs like to get users calendar info for exmaple
