### ISSUE TITLE
Is there an example of triggering the login process without a button?

### ISSUE THREAD

**Issue by jasonhilldm** [MomenSherif/react-oauth#68]
The demos seem to be user-initiated via the click of a button. Is it possible to automatically trigger the login without the user having to initiate it? Essentially, I want to automatically redirect the user to the Google login process if they try and access certain content that is protected behind an organisation Google login.

**Comment by jasonhilldm** [comment]
Maybe I misunderstood your suggestion, but I tried the following and got an error "React Hook "useGoogleLogin" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks":

    useEffect(() => {
        useGoogleLogin({
            ux_mode: "redirect",
            redirect_uri: "<my redirect url>"
        });
    }, []);

**Comment by MomenSherif** [comment]
```jsx

const loginWithGoogle =   useGoogleLogin({
        ux_mode: "redirect",
        redirect_uri: "<my redirect url>"
    });
    
  useEffect(() => {
   loginWithGoogle()
}, [loginWithGoogle]);
```

**Comment by jasonhilldm** [comment]
Thanks for the code...I now get this error "Cannot read properties of undefined (reading 'requestAccessToken')".

**Comment by MomenSherif** [comment]
mmm interesting


I will give it a try tonight and will back to you

**Comment by jasonhilldm** [comment]
OK - thanks so much for your help.

**Comment by jasonhilldm** [comment]
There is a call to useEffect within useLoadGsiScript to create the script element for the GSI client. This isn't getting called when debugging - is that because we are already within a useEffect call from my code?

**Comment by MomenSherif** [comment]
the issue above `Cannot read properties of undefined (reading 'requestAccessToken')` because google script didn't load yet

stupid work around you can in the effect add slight delay with setTimeout then trigger loginWithGoogle


or you can listen for `onScriptLoadSuccess` on `GoogleOAuthProvider` then update a local state to true, that triggers an effect to run then it will fire loginWithGoogle

**Comment by MomenSherif** [comment]
useLoadGsiScript should be called once GoogleOAuthProvider mounts even you are not using `useGoogleLogin`

**Comment by jasonhilldm** [comment]
Listening for the onScriptLoadSuccess sounds like a good option - what's the correct way to subscribe to that event? I am wrapping the app in the <GoogleOAuthProvider> element but how would I then subscribe to that event a child function component?

**Comment by jasonhilldm** [comment]
I figured it out using the following code:

    const [googleScriptReady, setGoogleScriptReady] = useState(false);
    const googleLogin = useGoogleLogin({
        ux_mode: "redirect",
        redirect_uri: "https://localhost:44403/"
    });

    GoogleOAuthProvider({
        onScriptLoadSuccess: () => {
            setGoogleScriptReady(true);
        }
    });

    useEffect(() => {
        if (googleScriptReady) {
            googleLogin();
        }
    }, [googleScriptReady]);

However, this results in a popup blocked error in the browser because it is still trying to open the Google account login in a popup window even though the ux_mode is set to "redirect". Should ux_mode be causing the page to redirect to the Google login instead of opening a popup?

**Comment by MomenSherif** [comment]
add `flow: "auth-code" property, redirect mode is allowed only with authorization code flow, which will give you a code to exchange with your backend to `id`, `access` and `refresh` tokens

sorry for late response, had busy days

**Comment by jasonhilldm** [comment]
Brilliant...that works perfectly now. Thanks for all your help.

One thing I notice is that the redirect URL from Google OAuth does not include an expiration duration for the token. Is there any way to obtain that back from Google? I'm assuming it's OK to store this token in a cookie on the client - is that appropriate? Is there any example of best practices for storing and refreshing these tokens?

**Comment by MomenSherif** [comment]
when you obtain the authorization code, you can exchange it with the required token from your backend, and your backend sets the tokens each one in its own HTTPS secure only cookie with own expiration time,

and for each request backend can check the accessToken if is valid or not by extracting it from the cookies and validating it against google
