### ISSUE TITLE
onSuccess not triggered

### ISSUE THREAD

**Issue by roychshao** [MomenSherif/react-oauth#69]
Hello, I wonder if there is a solution to 'onSuccess' is not triggered while I set ux_mode='redirect'?

**Comment by MomenSherif** [comment]
Redirecting will add code as query params after successful login onSuccess only triggers on popup mode

**Comment by roychshao** [comment]
@MomenSherif Ok I got it, thanks for your help!

**Comment by rehanpunjwani** [comment]
@MomenSherif Is the redirect flow doesn't work with GoogleLogin component? I can't see the prop to set the redirect uri.
