### ISSUE TITLE
how to get user info

### ISSUE THREAD

**Issue by emekaokoli** [MomenSherif/react-oauth#70]
Hi, great work you are doing, please how do I get the logged-in user info like photo, name etc?

Thank you.
Emeka.

**Comment by emekaokoli** [comment]
I figured I could just decode the token with jwt-decoded npm package.

**Comment by LogeswaranA** [comment]
I am unable to decode user info, when I pass jwt-decode. Can someone please assist here?. 
Jwt-decode library does nothing. 

i tried to pass access_token as it is and along with "Bearer".

**Comment by LogeswaranA** [comment]
Thanks, I got the information from other issue.. Just posting here for others to get benefit...

const login = useGoogleLogin({
   onSuccess: async (res) => {
     const { data } = await axios(
       "https://www.googleapis.com/oauth2/v3/userinfo",
       {
         headers: {
           Authorization: `Bearer ${res?.access_token}`,
         },
       }
     );
     console.log(data);
   },
 });
