### ISSUE TITLE
Add className or style for custom GoogleLogin

### ISSUE THREAD

**Issue by nhatran406** [MomenSherif/react-oauth#72]
I want to get credential from GoogleLogin and customize a little bit Icon Button. Please open help me class for custom to iframe.

**Comment by MomenSherif** [comment]
It's not possible to add class through the iframe, you can only customize the button with certain props allowed by google you can check GoogleLoginProps in README 

or for mor customization you can use the custom hook

**Comment by nhatran406** [comment]
With hook, I can not receive credential, just auth or token. Could you get me other way to do that?

**Comment by MomenSherif** [comment]
Check for styling props on GoogleLogin may you find what you want if not

And you will use custom hook
You can follow Authorization in https://react-oauth.vercel.app
will give you code snippets on how to get everything in different ways

**Comment by im-amir** [comment]
@nhatran406 
You can use the Implicit flow as @MomenSherif mentioned like this:
`
const googleLogin = useGoogleLogin({
  onSuccess: async (tokenResponse) => {
    console.log(tokenResponse);
    const userInfo = await axios.get(
      'https://www.googleapis.com/oauth2/v3/userinfo',
      { headers: { Authorization: 'Bearer <tokenResponse.access_token>' } },
    );

    console.log(userInfo);
  },
  onError: errorResponse => console.log(errorResponse),
});`


<MyCustomButton onClick={googleLogin}>

</MyCustomButton>
