### ISSUE TITLE
[Question] why use 'useRef' instead of props

### ISSUE THREAD

**Issue by hyeongjun3** [MomenSherif/react-oauth#73]
hi. i'm newbie frontend develop. 
i have a question while studing your project

why did you use `useRef` in the below block? I think that it can also be used as props
Is it to deleting dependencies to hooks like `useEffect?`

https://github.com/MomenSherif/react-oauth/blob/176fe71b8f721b0dd42197d02041caa23ec42291/packages/%40react-oauth/google/src/GoogleLogin.tsx#L39-L43

sorry for my poor english skill

**Comment by MomenSherif** [comment]
Yes to avoid adding onSuccess in dep array as it will be new function with every render as you will pass it as inline function which will cause the effect to run. And at the same time need to have reference for the onSuccess function without memoizing it so this trick can help achieve that
