### ISSUE TITLE
Oauth2 becomes undefined when I logout from my react app 

### ISSUE THREAD

**Issue by shivamp1998** [MomenSherif/react-oauth#74]
This is the image of error
![image](https://user-images.githubusercontent.com/48366063/183576479-aa44ba53-a7e6-4e67-b5bf-ddfb696d20ae.png)

**Comment by shivamp1998** [comment]
It works perfectly during login

**Comment by shivamp1998** [comment]
live link of the app : https://og-frontend-engage.herokuapp.com/

**Comment by MomenSherif** [comment]
When you logout, do you unmount GoogleOAuthProvider ?

**Comment by shivamp1998** [comment]
No, how exactly do you unmount the GoogleOAuthProvider ?

**Comment by MomenSherif** [comment]
No i don't need to unmount it

If your repo is public, leave a link will check the code later

**Comment by shivamp1998** [comment]
It is a private repo, but I will attach the screenshot of code 
Google Button File :
![image](https://user-images.githubusercontent.com/48366063/183589852-b5212dcd-799c-45e2-ba1c-bd82ea162a94.png)
index.tsx File:
![image](https://user-images.githubusercontent.com/48366063/183590027-aa3607e0-7a37-488b-a8d8-2d71fdf8ba80.png)

**Comment by shivamp1998** [comment]
@MomenSherif  is there any fix for this

**Comment by MomenSherif** [comment]
Remove `id="google"` on the google button or change it, It conflicts with window.google that google injects 
any id on elements is also assigned to the global window

**Comment by shivamp1998** [comment]
Thanks a lot!!
