### ISSUE TITLE
Style and locale flashing

### ISSUE THREAD

**Issue by jpvg10** [MomenSherif/react-oauth#75]
Hello!
I don't know if I'm doing something wrong, but when I refresh the page, I can briefly see the button without styles and with the wrong locale.

![Recording 2022-08-12 at 15 15 53](https://user-images.githubusercontent.com/14153526/184352629-dabcaffc-82c6-4115-83aa-8cc0a3a9d8c4.gif)

My code is basically just:
```
<GoogleLogin
  onSuccess={(credentialResponse) => {
    loginWithGoogle(credentialResponse.credential);
  }}
  onError={() => {
    loginWithGoogle(null, false);
  }}
  locale={locale}
/>
```

Thanks in advance.

**Comment by MomenSherif** [comment]
Hello @jpvg10 , Unfortunately this issue from google side, I can't do anything to solve it :(

**Comment by jpvg10** [comment]
Oh I see... 😕
