### ISSUE TITLE
Failed POST request to play.google.com on signup

### ISSUE THREAD

**Issue by cowley05** [MomenSherif/react-oauth#76]
I tried out your library to authenticate with and I noticed in the console that there is a failed request to: 

`https://play.google.com/log?format=json&hasfast=true&authuser=0` getting back a 401

I am wondering firstly what this call is for and why it is being made?

And secondly why it is failing?

I also noticed this happens in your demo site too.

Any help would be great! Thanks

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/1880175/184842813-008fce32-9d96-4182-8480-702244cd049b.png">

**Comment by halimov-oa** [comment]
The same

**Comment by arthurbrazil** [comment]
Same error with me

**Comment by MomenSherif** [comment]
Interesting

Actually these requests and the button are all done from google side, we don't fire requests manually unfortunately

**Comment by CrazyNoodl** [comment]
The same for me, but there is no error in incognito mode, hm)
