### ISSUE TITLE
AdBlock block rendering in Safari iOS 15.6

### ISSUE THREAD

**Issue by rivaslive** [MomenSherif/react-oauth#78]
I want to start by congratulating the good work on this lib.

The problem is when you use the Safari browser with ad blockers on iOS. I have the following active ADBblockers that I downloaded from the app store.

*Ad Block Pro
*Ad Guard

These blockers disable the Google button, causing it to not SHOW when these blockers are active in Safari.

It would be necessary to try to indicate to these blockers that the google button is not an advertisement.

Note: if I use Chrome or disable AdBlockers, the button is displayed

**Comment by MomenSherif** [comment]
I'm sorry for that, But maybe they blocked google gsi script to load

you can listen for script loading onSuccess and onError from props on `GoogleOAuthProvider` to show for the user anything you like
