### ISSUE TITLE
Origin is not allowed for the given client ID when using a GoogleLogin button

### ISSUE THREAD

**Issue by liqwid** [MomenSherif/react-oauth#79]
Trying to use `<GoogleLogin />` button and getting a white screen with 403 error "The given origin is not allowed for the given client ID." after the popup tab opens.

I'm using `http://localhost:3000` origin, it's added to the Client ID.
Authorisation flows with this setup work fine.

I'm currently authenticated with this client id, so the problem is likely gracefully handling the fact that I'm already authenticated.
Expectedly button works fine in incognito, however, it throws the same error in a different chrome workspace.

**Comment by MomenSherif** [comment]
Make sure to add http://localhost & http://localhost::3000 to you allowed domain in google console

**Comment by liqwid** [comment]
Thanks for the reply, I implemented a different approach already, could be useful if somebody else encounters this issue

**Comment by Caruso33** [comment]
As MomentSherif mentioned adding `http://localhost/` did the trick.
