### ISSUE TITLE
profile.Obj missing from the success response

### ISSUE THREAD

**Issue by AbirSantra** [MomenSherif/react-oauth#8]
The response that I am getting after signing the user is an object with only three items: my client id, credential, and select_by. Shouldn't I get more information like the profile.Obj which contains user's name, email, display picture so that I can show them on my web app after the user signs in? Am I missing something?

**Comment by AbirSantra** [comment]
Sorry my bad, I just had to decode it using jwt-decode. I got all the details I wanted.

**Comment by MomenSherif** [comment]
I'm glad that worked for you. 🎉

Profile.Obj, was part of the old Google SDK

**Comment by coucoseth** [comment]
@AbirSantra could you  give an example?
