### ISSUE TITLE
onError Don't catch a very important error 

### ISSUE THREAD

**Issue by GilAkivaWebiya** [MomenSherif/react-oauth#81]
I noticed an error when i click on the button(using custom button) to connect with google account
i don't get an error when i don't connected to the google login and i close the google login popup. 
And it's very necessary to get any response to this situation.

Any help would be great! Thanks

**Comment by Rayhan926** [comment]
I am also getting the same issue, onError function is not calling when I am closing the popup in useGoogleLogin hook

**Comment by MomenSherif** [comment]
Closing the popup is not supposed to be an error

anyway google controls all behavior about popup, It will fire an error only if the user started logging and cancelled the process in the middle
