### ISSUE TITLE
Does GoogleLogin component use Google Identity Services SDK?

### ISSUE THREAD

**Issue by dylanlarrivee** [MomenSherif/react-oauth#82]
Hi,
Does GoogleLogin component use Google Identity Services SDK? I was looking at the source code and it does not look like it does compared to the setup for the `useGoogleLogin` hook but I am pretty new to this google auth setup so wasnt sure if I was missing something. 

I am looking to migrate to Google Identity Services SDK but running into some issue getting it to integrate into my FusionAuth setup.

Thanks,
Dylan

**Comment by MomenSherif** [comment]
Hello @dylanlarrivee 

Yes it does, you can look for useLoadGsiScript it loads the gsi google script in the head

**Comment by dylanlarrivee** [comment]
Ok perfect. I realize I had my google scripts mixed up for what I was comparing to.

Is it possible to customize the button with the `GoogleLogin` component? I see you can withe the `useGoogleLogin` hook but that returns either an `access_token` or authorization code without setting a `redirect_uri` for popup ux which is needed for the fusionauth integration I have. The  `GoogleLogin` component seems to return a token in the format I need.

**Comment by MomenSherif** [comment]
Google provide some style props, like size, theme, text and shape

We don't have full control, but these can make the job done, please refer to Google Login props table in README

or for full control you can use the custom hook with authorization code flow then exchange the code with your backend which will return you JWT similar from GoogleLogin component

**Comment by dylanlarrivee** [comment]
Sounds good and thank you for the quick response.
