### ISSUE TITLE
README.md Documentation error

### ISSUE THREAD

**Issue by innovatorved** [MomenSherif/react-oauth#83]
## **Error in One Tap login Code**

> Error

![image](https://user-images.githubusercontent.com/65329423/188127879-64950b80-aad3-4697-bcaa-6947cb4b264b.png)

> Correct

### Correct code
```javascript
import { useGoogleOneTapLogin } from "@react-oauth/google";

useGoogleOneTapLogin({
    onSuccess: (credentialResponse) => {
      console.log(credentialResponse);
    },
    onError: () => {
      console.log("Login Failed");
    },
  });
```

Note : Error in JSON formatting

**Comment by MomenSherif** [comment]
Thanks @innovatorved It's fixed now
