### ISSUE TITLE
Message in console

### ISSUE THREAD

**Issue by viheag** [MomenSherif/react-oauth#84]
I'm using 'Sign-in Flow' but the console shows the following error

**
> POST Failed to load resource: the server responded with a status of 401 ()
   https://play.google.com/log?format=json&hasfast=true&authuser=0
**

**Comment by adeel-ali-atp** [comment]
same for me, no idea why it is there

**Comment by MomenSherif** [comment]
Actually, these requests and the button are all done from Google side, we don't fire requests manually unfortunately
