### ISSUE TITLE
access_type: "offline" does not return refresh token. 

### ISSUE THREAD

**Issue by Nrohit12** [MomenSherif/react-oauth#86]
I need refresh_token in the response values on successful google login. But including "access_type":"offline" does not seem to be working as referenced on Google. It would have been nice if we had "access_type" in the list of parameters.

**Comment by MomenSherif** [comment]
You can follow the Authorization code flow, to obtain `code` and exchange it from your backend with access, refresh and id tokens

**Comment by MomenSherif** [comment]
https://react-oauth.vercel.app/
