### ISSUE TITLE
unable to use -- useGoogleLogin 

### ISSUE THREAD

**Issue by jawed7siddiqui** [MomenSherif/react-oauth#90]
import { useGoogleLogin } from '@react-oauth/google';

const login = useGoogleLogin({
  onSuccess: tokenResponse => console.log(tokenResponse),
});

<MyCustomButton onClick={() => login()}>
  Sign in with Google 🚀{' '}
</MyCustomButton>;

can u plz give a complete example of useGoogleLogin ?

**Comment by MomenSherif** [comment]
Implicit flow is used in playground here 
https://github.com/MomenSherif/react-oauth/blob/master/apps/playground/src/components/ImplicitFlow.tsx

Authorization code flow
https://github.com/MomenSherif/react-oauth/blob/master/apps/playground/src/components/CodeFlow.tsx

and don't forget to wrap your app with GoogleOAuthProvider like this
https://github.com/MomenSherif/react-oauth/blob/master/apps/playground/src/index.tsx
and provide your clientId

**Comment by jawed7siddiqui** [comment]
Thnx , I got it & it's working 👍
