### ISSUE TITLE
How do I get IdToken in response from google

### ISSUE THREAD

**Issue by GhazanfarKhan** [MomenSherif/react-oauth#92]
Hi, I want to get IdToken in response from google, access_token is return in implicit flow.

**Comment by nekmart** [comment]
Same here, I need idToken. But it return only access_token

**Comment by chadallard** [comment]
If using idToken as bearer, the preferred method is to use access_token instead anyway. 

If you are relying on the extra data presented by the idToken, this data won't be available unless you make separate API calls to the "scope" you granted access to. There doesn't seem to be a way around this extra step, and I am in the same boat.

idToken is not presented as part of TokenResponse:
https://developers.google.com/identity/oauth2/web/reference/js-reference#TokenResponse 

As such, I will make separate API call to the scope to retrieve the data I need.

**Comment by GhazanfarKhan** [comment]
Basically I am using .net core identity so I need verify the token and add login to their tables. For that I am using 
Google.Apis.Auth package. 

```
public async Task<GoogleJsonWebSignature.Payload> VerifyGoogleToken(ExternalAuthViewModel externalAuth)
        {
            try
            {
                var settings = new GoogleJsonWebSignature.ValidationSettings()
                {
                    Audience = new List<string>() { googleAuthSettings.ClientId }
                };

                var payload = await GoogleJsonWebSignature.ValidateAsync(externalAuth.IdToken, settings);

                return payload;
            }
            catch (Exception)
            {
                //log an exception
                return null;
            }
        }
```
Here I need IdToken to verify.

**Comment by MomenSherif** [comment]
@GhazanfarKhan 

You can use authorization code flow better if you are going to communicate with your backend

code can be exchanged for id_token, access_token, refresh_token

implicit flow -> google will return only access_token to communicate with google APIs directly on the client

or you can use GoogleLogin button which will return id_token

**Comment by hieunv-0998** [comment]
@MomenSherif 

I have the same problem. Could you tell me how to exchange code and id_token, please? :bow: 
I searched and found nothing about it. :(

**Comment by D10100111001** [comment]
@MomenSherif I'm running in to this issue as well... I agree that the GoogleLogin button returns the `id_token` but I want to customize the button for which I use to use the `useGoogleLogin` hook. This hook does not have the `id_token` property.

**Comment by MomenSherif** [comment]
@D10100111001 If you are going with implicit flow -> you can send request to google to fetch user info
or you can use authorization code flow and exchange code with backend for id, access & refresh tokens

You can find examples here
https://react-oauth.vercel.app/
