### ISSUE TITLE
Do you support keeping user signed in?

### ISSUE THREAD

**Issue by ievgennaida** [MomenSherif/react-oauth#93]
I would like to avoid automatic logout during the application usage.
Do you support report user activity by the refreshing tokens  like it's proposed by the google auth flow?

**Comment by MomenSherif** [comment]
Google is no longer storing user's logged in state,

It's our responsibility now to keep user logged in via normal state in the App (you can store it localstorage, cookies ...etc, the way you prefer)

for refresh token -> every login from authorization code after exchanging the code with your backend you will get new access & refresh tokens

**Comment by ievgennaida** [comment]
@MomenSherif backend is verifying a validity of the token provided by the front-end and tokens are requested via google API. 
Regarding the refresh tokens they are used to request a new token. Would be nice to have a common way using a Library to perform exchange of the refresh tokens while lib is wrapping Google api.

**Comment by MomenSherif** [comment]
You can check something like passport js

https://www.passportjs.org/

or you can use @react-oauth/google on the client and google-auth-library on the backend https://www.npmjs.com/package/google-auth-library

**Comment by ievgennaida** [comment]
@MomenSherif 
Those links are for the node.js implementation.
for the pure javascript app should be a way to call google services to refresh an access token.
I see that there are some comments, but still not clear whether it's supported:

https://github.com/google/google-api-javascript-client/issues/645

**Comment by ievgennaida** [comment]
From the doc:
https://developers.google.com/identity/oauth2/web/guides/use-token-model

`By design, access tokens have a short lifetime. If the access token expires prior to the end of the user's session, obtain a new token by calling requestAccessToken() from a user-driven event such as a button press.`

But calling this method is showing popup again, so not fully clear on how to continue a session.

**Comment by MomenSherif** [comment]
Google doesn't keep track of the user login state, we need to handle this ourselves
