### ISSUE TITLE
Unable to get ID token with Custom login button (implicit & authorization code flow)

### ISSUE THREAD

**Issue by hieunv-0998** [MomenSherif/react-oauth#97]
I would like to retrieve the ID token for verifying in the back-end server.
But it seems that neither TokenResponse nor CodeResponse contains it.
Please support the ID token for the custom login button! Thank you!

References:
https://developers.google.com/identity/gsi/web/reference/js-reference#credential
https://developers.google.com/identity/oauth2/web/reference/js-reference#TokenResponse
https://developers.google.com/identity/oauth2/web/reference/js-reference#CodeResponse

**Comment by MomenSherif** [comment]
For custom login, you can go with authorization code flow and exchange the code in the backend (verify step) and will be exchanged for all tokens you need
