### ISSUE TITLE
[GSI_LOGGER]: The given origin is not allowed for the given client ID.

### ISSUE THREAD

**Issue by cristianmitran** [MomenSherif/react-oauth#98]
I am using <GoogleLogin> within a React.Component but I am getting the error "[GSI_LOGGER]: The given origin is not allowed for the given client ID."
I have correctly configured the "Authorized JavaScript origins" and "Authorized redirect URIs" to include the http://localhost:3000.

The URL after I click Login is
https://accounts.google.com/gsi/select?client_id=***&ux_mode=popup&ui_mode=card&as=***&channel_id=***&origin=http://localhost:3000&authuser=0

**Comment by MomenSherif** [comment]
Try to add it twice once with port 3000 and one without port

**Comment by cristianmitran** [comment]
Your suggestion has worked. Thank you!

**Comment by cristianmitran** [comment]
Your suggestion has worked. Thank you!

**Comment by Adityarauthan2409** [comment]
> Try to add it twice once with port 3000 and one without port

thanks buddy

**Comment by nch3ng** [comment]
I'm surprised that this isn't in the document.
